# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from woosh_msgs/AutoDockResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AutoDockResult(genpy.Message):
  _md5sum = "d8ec9fafe10e6a566804e6743191ffd0"
  _type = "woosh_msgs/AutoDockResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
uint64  err_msg

int32   result
int32   CANCLE = 1
int32   SUCCESS = 2
int32   FAILED = 3

uint8   roller_direction
uint8   LEFT = 11
uint8   RIGHT = 12
uint8   FRONT = 13
uint8   BACK = 14
"""
  # Pseudo-constants
  CANCLE = 1
  SUCCESS = 2
  FAILED = 3
  LEFT = 11
  RIGHT = 12
  FRONT = 13
  BACK = 14

  __slots__ = ['err_msg','result','roller_direction']
  _slot_types = ['uint64','int32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       err_msg,result,roller_direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AutoDockResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.err_msg is None:
        self.err_msg = 0
      if self.result is None:
        self.result = 0
      if self.roller_direction is None:
        self.roller_direction = 0
    else:
      self.err_msg = 0
      self.result = 0
      self.roller_direction = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_QiB().pack(_x.err_msg, _x.result, _x.roller_direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.err_msg, _x.result, _x.roller_direction,) = _get_struct_QiB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_QiB().pack(_x.err_msg, _x.result, _x.roller_direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.err_msg, _x.result, _x.roller_direction,) = _get_struct_QiB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_QiB = None
def _get_struct_QiB():
    global _struct_QiB
    if _struct_QiB is None:
        _struct_QiB = struct.Struct("<QiB")
    return _struct_QiB
