# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from woosh_msgs/NavigationModeGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NavigationModeGoal(genpy.Message):
  _md5sum = "6b3a848f30a01f4b14655f430e1f898f"
  _type = "woosh_msgs/NavigationModeGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
uint32 id		#通道id
uint8 navigation_mode  # 导航模式 0： 模糊避让导航 1：精准避让导航 2：停等导航 3：等待避让导航，等待一定时间之后，再执行避让
float32 waiting_timeout # 导航模式为3时（等待避让），时间必须大于0
float32 max_speed       #最大的导航速度
bool permitted_passage  #允许通行，路径变更之后，是否允许通行，如果允许则可以按照新的路径行走，否则不允许沿变更路径行走
uint32 capacity		#通道车量
uint32 nav_dir          # 导航方向 0： 默认底层自主决定导航方向，1： 前进导航，2：后退导航, 3: 沿着路经方向走（路经在前面就前进导航，路经在后面就是后退导航）
"""
  __slots__ = ['id','navigation_mode','waiting_timeout','max_speed','permitted_passage','capacity','nav_dir']
  _slot_types = ['uint32','uint8','float32','float32','bool','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,navigation_mode,waiting_timeout,max_speed,permitted_passage,capacity,nav_dir

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NavigationModeGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.navigation_mode is None:
        self.navigation_mode = 0
      if self.waiting_timeout is None:
        self.waiting_timeout = 0.
      if self.max_speed is None:
        self.max_speed = 0.
      if self.permitted_passage is None:
        self.permitted_passage = False
      if self.capacity is None:
        self.capacity = 0
      if self.nav_dir is None:
        self.nav_dir = 0
    else:
      self.id = 0
      self.navigation_mode = 0
      self.waiting_timeout = 0.
      self.max_speed = 0.
      self.permitted_passage = False
      self.capacity = 0
      self.nav_dir = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IB2fB2I().pack(_x.id, _x.navigation_mode, _x.waiting_timeout, _x.max_speed, _x.permitted_passage, _x.capacity, _x.nav_dir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.id, _x.navigation_mode, _x.waiting_timeout, _x.max_speed, _x.permitted_passage, _x.capacity, _x.nav_dir,) = _get_struct_IB2fB2I().unpack(str[start:end])
      self.permitted_passage = bool(self.permitted_passage)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IB2fB2I().pack(_x.id, _x.navigation_mode, _x.waiting_timeout, _x.max_speed, _x.permitted_passage, _x.capacity, _x.nav_dir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.id, _x.navigation_mode, _x.waiting_timeout, _x.max_speed, _x.permitted_passage, _x.capacity, _x.nav_dir,) = _get_struct_IB2fB2I().unpack(str[start:end])
      self.permitted_passage = bool(self.permitted_passage)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IB2fB2I = None
def _get_struct_IB2fB2I():
    global _struct_IB2fB2I
    if _struct_IB2fB2I is None:
        _struct_IB2fB2I = struct.Struct("<IB2fB2I")
    return _struct_IB2fB2I
