# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from woosh_msgs/StepCtrlAvoidObstacleGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class StepCtrlAvoidObstacleGoal(genpy.Message):
  _md5sum = "56a5d77f69f864e965f115583cda9633"
  _type = "woosh_msgs/StepCtrlAvoidObstacleGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float32  arg #参数
float32  speed #速度
int32    arg_type #arg_type=1：arg表示距离，正值往前，负值往后; arg_type=2：arg表示原地旋转弧度
int32    mode  #mode=1:action控制移动 mode=2:action不控制移动，反馈最近障碍物距离
int32    timeout #检测到障碍物停等超时时间

"""
  __slots__ = ['arg','speed','arg_type','mode','timeout']
  _slot_types = ['float32','float32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arg,speed,arg_type,mode,timeout

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StepCtrlAvoidObstacleGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.arg is None:
        self.arg = 0.
      if self.speed is None:
        self.speed = 0.
      if self.arg_type is None:
        self.arg_type = 0
      if self.mode is None:
        self.mode = 0
      if self.timeout is None:
        self.timeout = 0
    else:
      self.arg = 0.
      self.speed = 0.
      self.arg_type = 0
      self.mode = 0
      self.timeout = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f3i().pack(_x.arg, _x.speed, _x.arg_type, _x.mode, _x.timeout))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.arg, _x.speed, _x.arg_type, _x.mode, _x.timeout,) = _get_struct_2f3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f3i().pack(_x.arg, _x.speed, _x.arg_type, _x.mode, _x.timeout))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.arg, _x.speed, _x.arg_type, _x.mode, _x.timeout,) = _get_struct_2f3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f3i = None
def _get_struct_2f3i():
    global _struct_2f3i
    if _struct_2f3i is None:
        _struct_2f3i = struct.Struct("<2f3i")
    return _struct_2f3i
