(cl:in-package woosh_msgs-msg)
(cl:export '(ID-VAL
          ID
          TYPE-VAL
          TYPE
          SLOPE_ANGLE-VAL
          SLOPE_ANGLE
          SLOPE_ARROW-VAL
          SLOPE_ARROW
          CAPACITY-VAL
          CAPACITY
          WAIT_TIME_OUT-VAL
          WAIT_TIME_OUT
          NAV_MODE-VAL
          NAV_MODE
          MAX_SPEED-VAL
          MAX_SPEED
          DIRECTION-VAL
          DIRECTION
          RADIUS-VAL
          RADIUS
          OFFSET-VAL
          OFFSET
          VERTEX-VAL
          VERTEX
          NAV_POS-VAL
          NAV_POS
          ENTRY-VAL
          ENTRY
          EXTRANCE-VAL
          EXTRANCE
))