(cl:in-package woosh_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LINEARX-VAL
          LINEARX
          LINEARY-VAL
          LINEARY
          ANGULARZ-VAL
          ANGULARZ
          ODOMETRYX-VAL
          ODOMETRYX
          ODOMETRYY-VAL
          ODOMETRYY
          ODOMETRYTHETA-VAL
          ODOMETRYTHETA
          ODOMETRYIMUTHETA-VAL
          ODOMETRYIMUTHETA
          ODOMETRYLINEARX-VAL
          ODOMETRYLINEARX
          ODOMETRYLINEARY-VAL
          ODOMETRYLINEARY
          ODOMETRYANGULARZ-VAL
          ODOMETRYANGULARZ
          PWMLEFT-VAL
          PWMLEFT
          PWMRIGHT-VAL
          PWMRIGHT
          RSPEEDLEFT-VAL
          RSPEEDLEFT
          RSPEEDRIGHT-VAL
          RSPEEDRIGHT
          PULSELEFT-VAL
          PULSELEFT
          PULSERIGHT-VAL
          PULSERIGHT
          ERRORTYPE-VAL
          ERRORTYPE
          ERRORSTATUS-VAL
          ERRORSTATUS
))