; Auto-generated. Do not edit!


(cl:in-package woosh_msgs-msg)


;//! \htmlinclude ArTrackChargeFeedback.msg.html

(cl:defclass <ArTrackChargeFeedback> (roslisp-msg-protocol:ros-message)
  ((statusCode
    :reader statusCode
    :initarg :statusCode
    :type cl:integer
    :initform 0))
)

(cl:defclass ArTrackChargeFeedback (<ArTrackChargeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArTrackChargeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArTrackChargeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name woosh_msgs-msg:<ArTrackChargeFeedback> is deprecated: use woosh_msgs-msg:ArTrackChargeFeedback instead.")))

(cl:ensure-generic-function 'statusCode-val :lambda-list '(m))
(cl:defmethod statusCode-val ((m <ArTrackChargeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:statusCode-val is deprecated.  Use woosh_msgs-msg:statusCode instead.")
  (statusCode m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArTrackChargeFeedback>) ostream)
  "Serializes a message object of type '<ArTrackChargeFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'statusCode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'statusCode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'statusCode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'statusCode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'statusCode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'statusCode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'statusCode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'statusCode)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArTrackChargeFeedback>) istream)
  "Deserializes a message object of type '<ArTrackChargeFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'statusCode)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArTrackChargeFeedback>)))
  "Returns string type for a message object of type '<ArTrackChargeFeedback>"
  "woosh_msgs/ArTrackChargeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArTrackChargeFeedback)))
  "Returns string type for a message object of type 'ArTrackChargeFeedback"
  "woosh_msgs/ArTrackChargeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArTrackChargeFeedback>)))
  "Returns md5sum for a message object of type '<ArTrackChargeFeedback>"
  "ac52dbb349386b351af425b494e5f934")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArTrackChargeFeedback)))
  "Returns md5sum for a message object of type 'ArTrackChargeFeedback"
  "ac52dbb349386b351af425b494e5f934")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArTrackChargeFeedback>)))
  "Returns full string definition for message of type '<ArTrackChargeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint64 statusCode #状态码~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArTrackChargeFeedback)))
  "Returns full string definition for message of type 'ArTrackChargeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint64 statusCode #状态码~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArTrackChargeFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArTrackChargeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ArTrackChargeFeedback
    (cl:cons ':statusCode (statusCode msg))
))
