; Auto-generated. Do not edit!


(cl:in-package woosh_msgs-msg)


;//! \htmlinclude SecondPositionGoal.msg.html

(cl:defclass <SecondPositionGoal> (roslisp-msg-protocol:ros-message)
  ((mode
    :reader mode
    :initarg :mode
    :type cl:fixnum
    :initform 0)
   (executeMode
    :reader executeMode
    :initarg :executeMode
    :type cl:fixnum
    :initform 0)
   (rfid
    :reader rfid
    :initarg :rfid
    :type cl:fixnum
    :initform 0))
)

(cl:defclass SecondPositionGoal (<SecondPositionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SecondPositionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SecondPositionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name woosh_msgs-msg:<SecondPositionGoal> is deprecated: use woosh_msgs-msg:SecondPositionGoal instead.")))

(cl:ensure-generic-function 'mode-val :lambda-list '(m))
(cl:defmethod mode-val ((m <SecondPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:mode-val is deprecated.  Use woosh_msgs-msg:mode instead.")
  (mode m))

(cl:ensure-generic-function 'executeMode-val :lambda-list '(m))
(cl:defmethod executeMode-val ((m <SecondPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:executeMode-val is deprecated.  Use woosh_msgs-msg:executeMode instead.")
  (executeMode m))

(cl:ensure-generic-function 'rfid-val :lambda-list '(m))
(cl:defmethod rfid-val ((m <SecondPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:rfid-val is deprecated.  Use woosh_msgs-msg:rfid instead.")
  (rfid m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<SecondPositionGoal>)))
    "Constants for message type '<SecondPositionGoal>"
  '((:CANCEL . 0)
    (:EXCUTE . 1)
    (:PAUSE . 2)
    (:RESUM . 3)
    (:MAG_FRONT . 1)
    (:MAG_BACK . 2)
    (:RFID_FRONT . 3)
    (:RFID_BACK . 4))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'SecondPositionGoal)))
    "Constants for message type 'SecondPositionGoal"
  '((:CANCEL . 0)
    (:EXCUTE . 1)
    (:PAUSE . 2)
    (:RESUM . 3)
    (:MAG_FRONT . 1)
    (:MAG_BACK . 2)
    (:RFID_FRONT . 3)
    (:RFID_BACK . 4))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SecondPositionGoal>) ostream)
  "Serializes a message object of type '<SecondPositionGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'mode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executeMode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'rfid)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'rfid)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SecondPositionGoal>) istream)
  "Deserializes a message object of type '<SecondPositionGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'mode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executeMode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'rfid)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'rfid)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SecondPositionGoal>)))
  "Returns string type for a message object of type '<SecondPositionGoal>"
  "woosh_msgs/SecondPositionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SecondPositionGoal)))
  "Returns string type for a message object of type 'SecondPositionGoal"
  "woosh_msgs/SecondPositionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SecondPositionGoal>)))
  "Returns md5sum for a message object of type '<SecondPositionGoal>"
  "2a14afb1e26891f663c3e7245eb4e2b7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SecondPositionGoal)))
  "Returns md5sum for a message object of type 'SecondPositionGoal"
  "2a14afb1e26891f663c3e7245eb4e2b7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SecondPositionGoal>)))
  "Returns full string definition for message of type '<SecondPositionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 mode~%uint8 executeMode~%uint16 rfid~%~%#mode~%uint8 CANCEL = 0~%uint8 EXCUTE = 1~%uint8 PAUSE = 2~%uint8 RESUM = 3~%~%#executeMode~%uint8 MAG_FRONT = 1~%uint8 MAG_BACK = 2~%uint8 RFID_FRONT = 3~%uint8 RFID_BACK = 4~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SecondPositionGoal)))
  "Returns full string definition for message of type 'SecondPositionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 mode~%uint8 executeMode~%uint16 rfid~%~%#mode~%uint8 CANCEL = 0~%uint8 EXCUTE = 1~%uint8 PAUSE = 2~%uint8 RESUM = 3~%~%#executeMode~%uint8 MAG_FRONT = 1~%uint8 MAG_BACK = 2~%uint8 RFID_FRONT = 3~%uint8 RFID_BACK = 4~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SecondPositionGoal>))
  (cl:+ 0
     1
     1
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SecondPositionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SecondPositionGoal
    (cl:cons ':mode (mode msg))
    (cl:cons ':executeMode (executeMode msg))
    (cl:cons ':rfid (rfid msg))
))
