; Auto-generated. Do not edit!


(cl:in-package woosh_msgs-msg)


;//! \htmlinclude StepCtrlAvoidObstacleActionGoal.msg.html

(cl:defclass <StepCtrlAvoidObstacleActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type woosh_msgs-msg:StepCtrlAvoidObstacleGoal
    :initform (cl:make-instance 'woosh_msgs-msg:StepCtrlAvoidObstacleGoal)))
)

(cl:defclass StepCtrlAvoidObstacleActionGoal (<StepCtrlAvoidObstacleActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StepCtrlAvoidObstacleActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StepCtrlAvoidObstacleActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name woosh_msgs-msg:<StepCtrlAvoidObstacleActionGoal> is deprecated: use woosh_msgs-msg:StepCtrlAvoidObstacleActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <StepCtrlAvoidObstacleActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:header-val is deprecated.  Use woosh_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <StepCtrlAvoidObstacleActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:goal_id-val is deprecated.  Use woosh_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <StepCtrlAvoidObstacleActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:goal-val is deprecated.  Use woosh_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StepCtrlAvoidObstacleActionGoal>) ostream)
  "Serializes a message object of type '<StepCtrlAvoidObstacleActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StepCtrlAvoidObstacleActionGoal>) istream)
  "Deserializes a message object of type '<StepCtrlAvoidObstacleActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StepCtrlAvoidObstacleActionGoal>)))
  "Returns string type for a message object of type '<StepCtrlAvoidObstacleActionGoal>"
  "woosh_msgs/StepCtrlAvoidObstacleActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StepCtrlAvoidObstacleActionGoal)))
  "Returns string type for a message object of type 'StepCtrlAvoidObstacleActionGoal"
  "woosh_msgs/StepCtrlAvoidObstacleActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StepCtrlAvoidObstacleActionGoal>)))
  "Returns md5sum for a message object of type '<StepCtrlAvoidObstacleActionGoal>"
  "98d53dad324c71d21a7234304e3c43a2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StepCtrlAvoidObstacleActionGoal)))
  "Returns md5sum for a message object of type 'StepCtrlAvoidObstacleActionGoal"
  "98d53dad324c71d21a7234304e3c43a2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StepCtrlAvoidObstacleActionGoal>)))
  "Returns full string definition for message of type '<StepCtrlAvoidObstacleActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%StepCtrlAvoidObstacleGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: woosh_msgs/StepCtrlAvoidObstacleGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32  arg #参数~%float32  speed #速度~%int32    arg_type #arg_type=1：arg表示距离，正值往前，负值往后; arg_type=2：arg表示原地旋转弧度~%int32    mode  #mode=1:action控制移动 mode=2:action不控制移动，反馈最近障碍物距离~%int32    timeout #检测到障碍物停等超时时间~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StepCtrlAvoidObstacleActionGoal)))
  "Returns full string definition for message of type 'StepCtrlAvoidObstacleActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%StepCtrlAvoidObstacleGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: woosh_msgs/StepCtrlAvoidObstacleGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32  arg #参数~%float32  speed #速度~%int32    arg_type #arg_type=1：arg表示距离，正值往前，负值往后; arg_type=2：arg表示原地旋转弧度~%int32    mode  #mode=1:action控制移动 mode=2:action不控制移动，反馈最近障碍物距离~%int32    timeout #检测到障碍物停等超时时间~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StepCtrlAvoidObstacleActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StepCtrlAvoidObstacleActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StepCtrlAvoidObstacleActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
