; Auto-generated. Do not edit!


(cl:in-package woosh_msgs-msg)


;//! \htmlinclude StepCtrlAvoidObstacleFeedback.msg.html

(cl:defclass <StepCtrlAvoidObstacleFeedback> (roslisp-msg-protocol:ros-message)
  ((obstacle_distance
    :reader obstacle_distance
    :initarg :obstacle_distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass StepCtrlAvoidObstacleFeedback (<StepCtrlAvoidObstacleFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StepCtrlAvoidObstacleFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StepCtrlAvoidObstacleFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name woosh_msgs-msg:<StepCtrlAvoidObstacleFeedback> is deprecated: use woosh_msgs-msg:StepCtrlAvoidObstacleFeedback instead.")))

(cl:ensure-generic-function 'obstacle_distance-val :lambda-list '(m))
(cl:defmethod obstacle_distance-val ((m <StepCtrlAvoidObstacleFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:obstacle_distance-val is deprecated.  Use woosh_msgs-msg:obstacle_distance instead.")
  (obstacle_distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StepCtrlAvoidObstacleFeedback>) ostream)
  "Serializes a message object of type '<StepCtrlAvoidObstacleFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'obstacle_distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StepCtrlAvoidObstacleFeedback>) istream)
  "Deserializes a message object of type '<StepCtrlAvoidObstacleFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'obstacle_distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StepCtrlAvoidObstacleFeedback>)))
  "Returns string type for a message object of type '<StepCtrlAvoidObstacleFeedback>"
  "woosh_msgs/StepCtrlAvoidObstacleFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StepCtrlAvoidObstacleFeedback)))
  "Returns string type for a message object of type 'StepCtrlAvoidObstacleFeedback"
  "woosh_msgs/StepCtrlAvoidObstacleFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StepCtrlAvoidObstacleFeedback>)))
  "Returns md5sum for a message object of type '<StepCtrlAvoidObstacleFeedback>"
  "6c3bae86c954dc37799d101597cf8706")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StepCtrlAvoidObstacleFeedback)))
  "Returns md5sum for a message object of type 'StepCtrlAvoidObstacleFeedback"
  "6c3bae86c954dc37799d101597cf8706")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StepCtrlAvoidObstacleFeedback>)))
  "Returns full string definition for message of type '<StepCtrlAvoidObstacleFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%float32 obstacle_distance #最近障碍物距离~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StepCtrlAvoidObstacleFeedback)))
  "Returns full string definition for message of type 'StepCtrlAvoidObstacleFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%float32 obstacle_distance #最近障碍物距离~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StepCtrlAvoidObstacleFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StepCtrlAvoidObstacleFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StepCtrlAvoidObstacleFeedback
    (cl:cons ':obstacle_distance (obstacle_distance msg))
))
