; Auto-generated. Do not edit!


(cl:in-package woosh_msgs-msg)


;//! \htmlinclude TagLocalizationResult.msg.html

(cl:defclass <TagLocalizationResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0)
   (err_msg
    :reader err_msg
    :initarg :err_msg
    :type cl:string
    :initform ""))
)

(cl:defclass TagLocalizationResult (<TagLocalizationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TagLocalizationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TagLocalizationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name woosh_msgs-msg:<TagLocalizationResult> is deprecated: use woosh_msgs-msg:TagLocalizationResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <TagLocalizationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:result-val is deprecated.  Use woosh_msgs-msg:result instead.")
  (result m))

(cl:ensure-generic-function 'err_msg-val :lambda-list '(m))
(cl:defmethod err_msg-val ((m <TagLocalizationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:err_msg-val is deprecated.  Use woosh_msgs-msg:err_msg instead.")
  (err_msg m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TagLocalizationResult>) ostream)
  "Serializes a message object of type '<TagLocalizationResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'err_msg))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'err_msg))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TagLocalizationResult>) istream)
  "Deserializes a message object of type '<TagLocalizationResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'err_msg) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'err_msg) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TagLocalizationResult>)))
  "Returns string type for a message object of type '<TagLocalizationResult>"
  "woosh_msgs/TagLocalizationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TagLocalizationResult)))
  "Returns string type for a message object of type 'TagLocalizationResult"
  "woosh_msgs/TagLocalizationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TagLocalizationResult>)))
  "Returns md5sum for a message object of type '<TagLocalizationResult>"
  "09aeb1bafb3b420fac75afd69de1c815")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TagLocalizationResult)))
  "Returns md5sum for a message object of type 'TagLocalizationResult"
  "09aeb1bafb3b420fac75afd69de1c815")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TagLocalizationResult>)))
  "Returns full string definition for message of type '<TagLocalizationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result    #0:成功,1:失败,2:取消~%string err_msg  #成功：SUCCESS，失败：具体失败原因~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TagLocalizationResult)))
  "Returns full string definition for message of type 'TagLocalizationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result    #0:成功,1:失败,2:取消~%string err_msg  #成功：SUCCESS，失败：具体失败原因~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TagLocalizationResult>))
  (cl:+ 0
     4
     4 (cl:length (cl:slot-value msg 'err_msg))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TagLocalizationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TagLocalizationResult
    (cl:cons ':result (result msg))
    (cl:cons ':err_msg (err_msg msg))
))
