; Auto-generated. Do not edit!


(cl:in-package woosh_msgs-msg)


;//! \htmlinclude TractorControlFeedback.msg.html

(cl:defclass <TractorControlFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:fixnum
    :initform 0)
   (executeMode
    :reader executeMode
    :initarg :executeMode
    :type cl:fixnum
    :initform 0))
)

(cl:defclass TractorControlFeedback (<TractorControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TractorControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TractorControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name woosh_msgs-msg:<TractorControlFeedback> is deprecated: use woosh_msgs-msg:TractorControlFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <TractorControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:feedback-val is deprecated.  Use woosh_msgs-msg:feedback instead.")
  (feedback m))

(cl:ensure-generic-function 'executeMode-val :lambda-list '(m))
(cl:defmethod executeMode-val ((m <TractorControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:executeMode-val is deprecated.  Use woosh_msgs-msg:executeMode instead.")
  (executeMode m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TractorControlFeedback>) ostream)
  "Serializes a message object of type '<TractorControlFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'feedback)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executeMode)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TractorControlFeedback>) istream)
  "Deserializes a message object of type '<TractorControlFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executeMode)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TractorControlFeedback>)))
  "Returns string type for a message object of type '<TractorControlFeedback>"
  "woosh_msgs/TractorControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TractorControlFeedback)))
  "Returns string type for a message object of type 'TractorControlFeedback"
  "woosh_msgs/TractorControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TractorControlFeedback>)))
  "Returns md5sum for a message object of type '<TractorControlFeedback>"
  "4046d8eceb4c4136d262ce19164fb6f7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TractorControlFeedback)))
  "Returns md5sum for a message object of type 'TractorControlFeedback"
  "4046d8eceb4c4136d262ce19164fb6f7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TractorControlFeedback>)))
  "Returns full string definition for message of type '<TractorControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 feedback~%uint8 executeMode~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TractorControlFeedback)))
  "Returns full string definition for message of type 'TractorControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 feedback~%uint8 executeMode~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TractorControlFeedback>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TractorControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TractorControlFeedback
    (cl:cons ':feedback (feedback msg))
    (cl:cons ':executeMode (executeMode msg))
))
