; Auto-generated. Do not edit!


(cl:in-package woosh_msgs-msg)


;//! \htmlinclude TractorControlResult.msg.html

(cl:defclass <TractorControlResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:fixnum
    :initform 0)
   (executeMode
    :reader executeMode
    :initarg :executeMode
    :type cl:fixnum
    :initform 0))
)

(cl:defclass TractorControlResult (<TractorControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TractorControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TractorControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name woosh_msgs-msg:<TractorControlResult> is deprecated: use woosh_msgs-msg:TractorControlResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <TractorControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:result-val is deprecated.  Use woosh_msgs-msg:result instead.")
  (result m))

(cl:ensure-generic-function 'executeMode-val :lambda-list '(m))
(cl:defmethod executeMode-val ((m <TractorControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader woosh_msgs-msg:executeMode-val is deprecated.  Use woosh_msgs-msg:executeMode instead.")
  (executeMode m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TractorControlResult>) ostream)
  "Serializes a message object of type '<TractorControlResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executeMode)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TractorControlResult>) istream)
  "Deserializes a message object of type '<TractorControlResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'executeMode)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TractorControlResult>)))
  "Returns string type for a message object of type '<TractorControlResult>"
  "woosh_msgs/TractorControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TractorControlResult)))
  "Returns string type for a message object of type 'TractorControlResult"
  "woosh_msgs/TractorControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TractorControlResult>)))
  "Returns md5sum for a message object of type '<TractorControlResult>"
  "6bc59990f85b93635cae46a24ddcf90e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TractorControlResult)))
  "Returns md5sum for a message object of type 'TractorControlResult"
  "6bc59990f85b93635cae46a24ddcf90e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TractorControlResult>)))
  "Returns full string definition for message of type '<TractorControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 result #1表示执行成功，负值表示执行失败~%uint8 executeMode~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TractorControlResult)))
  "Returns full string definition for message of type 'TractorControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 result #1表示执行成功，负值表示执行失败~%uint8 executeMode~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TractorControlResult>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TractorControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TractorControlResult
    (cl:cons ':result (result msg))
    (cl:cons ':executeMode (executeMode msg))
))
