// Auto-generated. Do not edit!

// (in-package woosh_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ArmFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.feedback = null;
      this.excute_type = null;
      this.statusCode = null;
    }
    else {
      if (initObj.hasOwnProperty('feedback')) {
        this.feedback = initObj.feedback
      }
      else {
        this.feedback = 0;
      }
      if (initObj.hasOwnProperty('excute_type')) {
        this.excute_type = initObj.excute_type
      }
      else {
        this.excute_type = 0;
      }
      if (initObj.hasOwnProperty('statusCode')) {
        this.statusCode = initObj.statusCode
      }
      else {
        this.statusCode = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ArmFeedback
    // Serialize message field [feedback]
    bufferOffset = _serializer.int8(obj.feedback, buffer, bufferOffset);
    // Serialize message field [excute_type]
    bufferOffset = _serializer.uint8(obj.excute_type, buffer, bufferOffset);
    // Serialize message field [statusCode]
    bufferOffset = _serializer.uint64(obj.statusCode, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ArmFeedback
    let len;
    let data = new ArmFeedback(null);
    // Deserialize message field [feedback]
    data.feedback = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [excute_type]
    data.excute_type = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [statusCode]
    data.statusCode = _deserializer.uint64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 10;
  }

  static datatype() {
    // Returns string type for a message object
    return 'woosh_msgs/ArmFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fcef967b5fd004acffc406f7c43aaa41';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int8 feedback #4暂停 5继续
    uint8 excute_type
    uint64   statusCode #状态码
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ArmFeedback(null);
    if (msg.feedback !== undefined) {
      resolved.feedback = msg.feedback;
    }
    else {
      resolved.feedback = 0
    }

    if (msg.excute_type !== undefined) {
      resolved.excute_type = msg.excute_type;
    }
    else {
      resolved.excute_type = 0
    }

    if (msg.statusCode !== undefined) {
      resolved.statusCode = msg.statusCode;
    }
    else {
      resolved.statusCode = 0
    }

    return resolved;
    }
};

module.exports = ArmFeedback;
