// Auto-generated. Do not edit!

// (in-package woosh_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ArTrackChargeActionGoal = require('./ArTrackChargeActionGoal.js');
let ArTrackChargeActionResult = require('./ArTrackChargeActionResult.js');
let ArTrackChargeActionFeedback = require('./ArTrackChargeActionFeedback.js');

//-----------------------------------------------------------

class ArTrackChargeAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new ArTrackChargeActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new ArTrackChargeActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new ArTrackChargeActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ArTrackChargeAction
    // Serialize message field [action_goal]
    bufferOffset = ArTrackChargeActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = ArTrackChargeActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = ArTrackChargeActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ArTrackChargeAction
    let len;
    let data = new ArTrackChargeAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = ArTrackChargeActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = ArTrackChargeActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = ArTrackChargeActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += ArTrackChargeActionGoal.getMessageSize(object.action_goal);
    length += ArTrackChargeActionResult.getMessageSize(object.action_result);
    length += ArTrackChargeActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'woosh_msgs/ArTrackChargeAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b6b9aee5493c07031eeb7f8bae462f27';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    ArTrackChargeActionGoal action_goal
    ArTrackChargeActionResult action_result
    ArTrackChargeActionFeedback action_feedback
    
    ================================================================================
    MSG: woosh_msgs/ArTrackChargeActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    ArTrackChargeGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: woosh_msgs/ArTrackChargeGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    int32 type
    int32 START = 0
    int32 PAUSE = 1  #暂停
    int32 RESUME = 2  #继续
    int32[] id_range #需要识别的二维码的ID范围
    float32[] marker_to_aimpoint
    float32[] aimpoint_to_target
    
    ================================================================================
    MSG: woosh_msgs/ArTrackChargeActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ArTrackChargeResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: woosh_msgs/ArTrackChargeResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    int32 result
    int32 SUCCESS = 0 #成功
    int32 FAIL = 1  #失败
    int32 CANCEL = 2 #取消
    float32 enter_distance
    uint64 statusCode #状态码
    
    ================================================================================
    MSG: woosh_msgs/ArTrackChargeActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ArTrackChargeFeedback feedback
    
    ================================================================================
    MSG: woosh_msgs/ArTrackChargeFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    uint64 statusCode #状态码
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ArTrackChargeAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = ArTrackChargeActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new ArTrackChargeActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = ArTrackChargeActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new ArTrackChargeActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = ArTrackChargeActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new ArTrackChargeActionFeedback()
    }

    return resolved;
    }
};

module.exports = ArTrackChargeAction;
