// Auto-generated. Do not edit!

// (in-package woosh_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MultiMapNavigationFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.wormhole_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('wormhole_feedback')) {
        this.wormhole_feedback = initObj.wormhole_feedback
      }
      else {
        this.wormhole_feedback = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MultiMapNavigationFeedback
    // Serialize message field [wormhole_feedback]
    bufferOffset = _serializer.int32(obj.wormhole_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MultiMapNavigationFeedback
    let len;
    let data = new MultiMapNavigationFeedback(null);
    // Deserialize message field [wormhole_feedback]
    data.wormhole_feedback = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'woosh_msgs/MultiMapNavigationFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '738bb9b8ff034276e8fc626342495d2b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 wormhole_feedback # 1: 到达虫洞成功，0：到达虫洞失败
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MultiMapNavigationFeedback(null);
    if (msg.wormhole_feedback !== undefined) {
      resolved.wormhole_feedback = msg.wormhole_feedback;
    }
    else {
      resolved.wormhole_feedback = 0
    }

    return resolved;
    }
};

module.exports = MultiMapNavigationFeedback;
