// Auto-generated. Do not edit!

// (in-package woosh_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RollerControlGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.mode = null;
      this.executeMode = null;
      this.connectMode = null;
    }
    else {
      if (initObj.hasOwnProperty('mode')) {
        this.mode = initObj.mode
      }
      else {
        this.mode = 0;
      }
      if (initObj.hasOwnProperty('executeMode')) {
        this.executeMode = initObj.executeMode
      }
      else {
        this.executeMode = 0;
      }
      if (initObj.hasOwnProperty('connectMode')) {
        this.connectMode = initObj.connectMode
      }
      else {
        this.connectMode = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RollerControlGoal
    // Serialize message field [mode]
    bufferOffset = _serializer.uint8(obj.mode, buffer, bufferOffset);
    // Serialize message field [executeMode]
    bufferOffset = _serializer.uint8(obj.executeMode, buffer, bufferOffset);
    // Serialize message field [connectMode]
    bufferOffset = _serializer.uint8(obj.connectMode, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RollerControlGoal
    let len;
    let data = new RollerControlGoal(null);
    // Deserialize message field [mode]
    data.mode = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [executeMode]
    data.executeMode = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [connectMode]
    data.connectMode = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 3;
  }

  static datatype() {
    // Returns string type for a message object
    return 'woosh_msgs/RollerControlGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c052de08f3408efa27d6c5e9c0917c63';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint8 mode
    uint8 executeMode
    uint8 connectMode
    
    #mode
    uint8 CANCEL = 0
    uint8 EXCUTE = 1
    uint8 PAUSE = 2
    uint8 RESUM = 3
    
    #executeMode
    uint8 FRONT_LOAD = 1
    uint8 FRONT_UNLOAD = 2
    uint8 BACK_LOAD = 3
    uint8 BACK_UNLOAD = 4
    
    #connectMode
    uint8 NONE = 0
    uint8 CHECK = 1
    uint8 PROCESSCTRL = 2
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RollerControlGoal(null);
    if (msg.mode !== undefined) {
      resolved.mode = msg.mode;
    }
    else {
      resolved.mode = 0
    }

    if (msg.executeMode !== undefined) {
      resolved.executeMode = msg.executeMode;
    }
    else {
      resolved.executeMode = 0
    }

    if (msg.connectMode !== undefined) {
      resolved.connectMode = msg.connectMode;
    }
    else {
      resolved.connectMode = 0
    }

    return resolved;
    }
};

// Constants for message
RollerControlGoal.Constants = {
  CANCEL: 0,
  EXCUTE: 1,
  PAUSE: 2,
  RESUM: 3,
  FRONT_LOAD: 1,
  FRONT_UNLOAD: 2,
  BACK_LOAD: 3,
  BACK_UNLOAD: 4,
  NONE: 0,
  CHECK: 1,
  PROCESSCTRL: 2,
}

module.exports = RollerControlGoal;
