// Auto-generated. Do not edit!

// (in-package woosh_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SecondPositionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result = null;
      this.executeMode = null;
      this.rfid = null;
      this.distance = null;
    }
    else {
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = 0;
      }
      if (initObj.hasOwnProperty('executeMode')) {
        this.executeMode = initObj.executeMode
      }
      else {
        this.executeMode = 0;
      }
      if (initObj.hasOwnProperty('rfid')) {
        this.rfid = initObj.rfid
      }
      else {
        this.rfid = 0;
      }
      if (initObj.hasOwnProperty('distance')) {
        this.distance = initObj.distance
      }
      else {
        this.distance = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SecondPositionResult
    // Serialize message field [result]
    bufferOffset = _serializer.int8(obj.result, buffer, bufferOffset);
    // Serialize message field [executeMode]
    bufferOffset = _serializer.uint8(obj.executeMode, buffer, bufferOffset);
    // Serialize message field [rfid]
    bufferOffset = _serializer.uint16(obj.rfid, buffer, bufferOffset);
    // Serialize message field [distance]
    bufferOffset = _serializer.float32(obj.distance, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SecondPositionResult
    let len;
    let data = new SecondPositionResult(null);
    // Deserialize message field [result]
    data.result = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [executeMode]
    data.executeMode = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [rfid]
    data.rfid = _deserializer.uint16(buffer, bufferOffset);
    // Deserialize message field [distance]
    data.distance = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'woosh_msgs/SecondPositionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '22f9023889607f03709a7d9307c04454';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int8 result #1表示执行成功，负值表示执行失败
    uint8 executeMode
    uint16 rfid
    float32 distance
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SecondPositionResult(null);
    if (msg.result !== undefined) {
      resolved.result = msg.result;
    }
    else {
      resolved.result = 0
    }

    if (msg.executeMode !== undefined) {
      resolved.executeMode = msg.executeMode;
    }
    else {
      resolved.executeMode = 0
    }

    if (msg.rfid !== undefined) {
      resolved.rfid = msg.rfid;
    }
    else {
      resolved.rfid = 0
    }

    if (msg.distance !== undefined) {
      resolved.distance = msg.distance;
    }
    else {
      resolved.distance = 0.0
    }

    return resolved;
    }
};

module.exports = SecondPositionResult;
