// Generated by gencpp from file woosh_msgs/ArTagPose.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_ARTAGPOSE_H
#define WOOSH_MSGS_MESSAGE_ARTAGPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Pose.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct ArTagPose_
{
  typedef ArTagPose_<ContainerAllocator> Type;

  ArTagPose_()
    : distination()
    , tag_pose()
    , tag_id(0)  {
    }
  ArTagPose_(const ContainerAllocator& _alloc)
    : distination(_alloc)
    , tag_pose(_alloc)
    , tag_id(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _distination_type;
  _distination_type distination;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _tag_pose_type;
  _tag_pose_type tag_pose;

   typedef int32_t _tag_id_type;
  _tag_id_type tag_id;





  typedef boost::shared_ptr< ::woosh_msgs::ArTagPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::ArTagPose_<ContainerAllocator> const> ConstPtr;

}; // struct ArTagPose_

typedef ::woosh_msgs::ArTagPose_<std::allocator<void> > ArTagPose;

typedef boost::shared_ptr< ::woosh_msgs::ArTagPose > ArTagPosePtr;
typedef boost::shared_ptr< ::woosh_msgs::ArTagPose const> ArTagPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::ArTagPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::ArTagPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::ArTagPose_<ContainerAllocator1> & lhs, const ::woosh_msgs::ArTagPose_<ContainerAllocator2> & rhs)
{
  return lhs.distination == rhs.distination &&
    lhs.tag_pose == rhs.tag_pose &&
    lhs.tag_id == rhs.tag_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::ArTagPose_<ContainerAllocator1> & lhs, const ::woosh_msgs::ArTagPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ArTagPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ArTagPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ArTagPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c61879d8040fe8796fb4042d4277e94";
  }

  static const char* value(const ::woosh_msgs::ArTagPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c61879d8040fe87ULL;
  static const uint64_t static_value2 = 0x96fb4042d4277e94ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/ArTagPose";
  }

  static const char* value(const ::woosh_msgs::ArTagPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point distination\n"
"geometry_msgs/Pose tag_pose\n"
"int32 tag_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::woosh_msgs::ArTagPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distination);
      stream.next(m.tag_pose);
      stream.next(m.tag_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArTagPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::ArTagPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::ArTagPose_<ContainerAllocator>& v)
  {
    s << indent << "distination: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.distination);
    s << indent << "tag_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.tag_pose);
    s << indent << "tag_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tag_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_ARTAGPOSE_H
