// Generated by gencpp from file woosh_msgs/ArTrackLocateResponse.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_ARTRACKLOCATERESPONSE_H
#define WOOSH_MSGS_MESSAGE_ARTRACKLOCATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <woosh_msgs/ArTagPose.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct ArTrackLocateResponse_
{
  typedef ArTrackLocateResponse_<ContainerAllocator> Type;

  ArTrackLocateResponse_()
    : success(false)
    , message()
    , ar_tag_pose()  {
    }
  ArTrackLocateResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , ar_tag_pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::woosh_msgs::ArTagPose_<ContainerAllocator>  _ar_tag_pose_type;
  _ar_tag_pose_type ar_tag_pose;





  typedef boost::shared_ptr< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArTrackLocateResponse_

typedef ::woosh_msgs::ArTrackLocateResponse_<std::allocator<void> > ArTrackLocateResponse;

typedef boost::shared_ptr< ::woosh_msgs::ArTrackLocateResponse > ArTrackLocateResponsePtr;
typedef boost::shared_ptr< ::woosh_msgs::ArTrackLocateResponse const> ArTrackLocateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.ar_tag_pose == rhs.ar_tag_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "343796bef7e4c0b5a4ec24bad8f1fdd2";
  }

  static const char* value(const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x343796bef7e4c0b5ULL;
  static const uint64_t static_value2 = 0xa4ec24bad8f1fdd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/ArTrackLocateResponse";
  }

  static const char* value(const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success   # indicate successful run of triggered service\n"
"string message # informational, e.g. for error messages\n"
"ArTagPose ar_tag_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/ArTagPose\n"
"geometry_msgs/Point distination\n"
"geometry_msgs/Pose tag_pose\n"
"int32 tag_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.ar_tag_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArTrackLocateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::ArTrackLocateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "ar_tag_pose: ";
    s << std::endl;
    Printer< ::woosh_msgs::ArTagPose_<ContainerAllocator> >::stream(s, indent + "  ", v.ar_tag_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_ARTRACKLOCATERESPONSE_H
