// Generated by gencpp from file woosh_msgs/AutoDock2ActionGoal.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_AUTODOCK2ACTIONGOAL_H
#define WOOSH_MSGS_MESSAGE_AUTODOCK2ACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <woosh_msgs/AutoDock2Goal.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct AutoDock2ActionGoal_
{
  typedef AutoDock2ActionGoal_<ContainerAllocator> Type;

  AutoDock2ActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  AutoDock2ActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::woosh_msgs::AutoDock2Goal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDock2ActionGoal_

typedef ::woosh_msgs::AutoDock2ActionGoal_<std::allocator<void> > AutoDock2ActionGoal;

typedef boost::shared_ptr< ::woosh_msgs::AutoDock2ActionGoal > AutoDock2ActionGoalPtr;
typedef boost::shared_ptr< ::woosh_msgs::AutoDock2ActionGoal const> AutoDock2ActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6ee68fecda028899c0e69399ea42ef4";
  }

  static const char* value(const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6ee68fecda02889ULL;
  static const uint64_t static_value2 = 0x9c0e69399ea42ef4ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/AutoDock2ActionGoal";
  }

  static const char* value(const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"AutoDock2Goal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDock2Goal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string  tag_no                      #tag编号\n"
"\n"
"int8    board_shape\n"
"int8    ALL_SHAPE = 0               #操作所有特征板\n"
"int8    VL_SHAPE = 1                #VL型特征板\n"
"int8    PARALLEL_SHAPE = 2          #平行特征板\n"
"int8    CONVEX_SHAPE = 3            #凸性特征板\n"
"int8    NARROW_PASSAGE_SHAPE = 4    #狭窄通道特征形状\n"
"int8    ELEVATOR_SHAPE = 5          #电梯口特征形状\n"
"int8    RECTANGLE_SHAPE = 6            #料车\n"
"\n"
"int8    type\n"
"int8    ENTER = 0\n"
"int8    PAUSE = 1\n"
"int8    RESUM = 2\n"
"int8    LEAVE = 3\n"
"int8    RESET = 4\n"
"\n"
"int8    dock_direction              #对接方向\n"
"int8    BACKWARD = 0\n"
"int8    FRONTWARD = 1\n"
"\n"
"geometry_msgs/Pose2D  targetPose    #当此接口用于狭窄通道的时候，此变量起作用。用于判断狭窄通道出口位置点。\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDock2ActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::woosh_msgs::AutoDock2Goal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_AUTODOCK2ACTIONGOAL_H
