// Generated by gencpp from file woosh_msgs/AutoDock2Action.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_AUTODOCK2ACTION_H
#define WOOSH_MSGS_MESSAGE_AUTODOCK2ACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <woosh_msgs/AutoDock2ActionGoal.h>
#include <woosh_msgs/AutoDock2ActionResult.h>
#include <woosh_msgs/AutoDock2ActionFeedback.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct AutoDock2Action_
{
  typedef AutoDock2Action_<ContainerAllocator> Type;

  AutoDock2Action_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  AutoDock2Action_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::woosh_msgs::AutoDock2ActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::woosh_msgs::AutoDock2ActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDock2Action_

typedef ::woosh_msgs::AutoDock2Action_<std::allocator<void> > AutoDock2Action;

typedef boost::shared_ptr< ::woosh_msgs::AutoDock2Action > AutoDock2ActionPtr;
typedef boost::shared_ptr< ::woosh_msgs::AutoDock2Action const> AutoDock2ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::AutoDock2Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::AutoDock2Action_<ContainerAllocator1> & lhs, const ::woosh_msgs::AutoDock2Action_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::AutoDock2Action_<ContainerAllocator1> & lhs, const ::woosh_msgs::AutoDock2Action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "546d2e58976fa398cde8e71fc80714b7";
  }

  static const char* value(const ::woosh_msgs::AutoDock2Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x546d2e58976fa398ULL;
  static const uint64_t static_value2 = 0xcde8e71fc80714b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/AutoDock2Action";
  }

  static const char* value(const ::woosh_msgs::AutoDock2Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"AutoDock2ActionGoal action_goal\n"
"AutoDock2ActionResult action_result\n"
"AutoDock2ActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDock2ActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"AutoDock2Goal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDock2Goal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string  tag_no                      #tag编号\n"
"\n"
"int8    board_shape\n"
"int8    ALL_SHAPE = 0               #操作所有特征板\n"
"int8    VL_SHAPE = 1                #VL型特征板\n"
"int8    PARALLEL_SHAPE = 2          #平行特征板\n"
"int8    CONVEX_SHAPE = 3            #凸性特征板\n"
"int8    NARROW_PASSAGE_SHAPE = 4    #狭窄通道特征形状\n"
"int8    ELEVATOR_SHAPE = 5          #电梯口特征形状\n"
"int8    RECTANGLE_SHAPE = 6            #料车\n"
"\n"
"int8    type\n"
"int8    ENTER = 0\n"
"int8    PAUSE = 1\n"
"int8    RESUM = 2\n"
"int8    LEAVE = 3\n"
"int8    RESET = 4\n"
"\n"
"int8    dock_direction              #对接方向\n"
"int8    BACKWARD = 0\n"
"int8    FRONTWARD = 1\n"
"\n"
"geometry_msgs/Pose2D  targetPose    #当此接口用于狭窄通道的时候，此变量起作用。用于判断狭窄通道出口位置点。\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDock2ActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"AutoDock2Result result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDock2Result\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint64  err_msg\n"
"\n"
"int8    result\n"
"int8    CANCLE = 1\n"
"int8    SUCCESS = 2\n"
"int8    FAILED = 3\n"
"\n"
"uint8   feature_direction\n"
"uint8   EMPTY = 0\n"
"uint8   LEFT = 1\n"
"uint8   RIGHT = 2\n"
"uint8   FRONT = 3\n"
"uint8   BACK = 4\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDock2ActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"AutoDock2Feedback feedback\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDock2Feedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint64  err_msg\n"
"\n"
"int8    status\n"
"int8    EXECUTING = 1\n"
"int8    PAUSE = 2\n"
"\n"
"int8    feedback\n"
"int8    ILLEGAL_GOAL = 1\n"
"int8    LEGAL_GOAL = 2\n"
"\n"
;
  }

  static const char* value(const ::woosh_msgs::AutoDock2Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDock2Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::AutoDock2Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::AutoDock2Action_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::woosh_msgs::AutoDock2ActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::woosh_msgs::AutoDock2ActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::woosh_msgs::AutoDock2ActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_AUTODOCK2ACTION_H
