// Generated by gencpp from file woosh_msgs/AutoDockActionGoal.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_AUTODOCKACTIONGOAL_H
#define WOOSH_MSGS_MESSAGE_AUTODOCKACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <woosh_msgs/AutoDockGoal.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct AutoDockActionGoal_
{
  typedef AutoDockActionGoal_<ContainerAllocator> Type;

  AutoDockActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  AutoDockActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::woosh_msgs::AutoDockGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockActionGoal_

typedef ::woosh_msgs::AutoDockActionGoal_<std::allocator<void> > AutoDockActionGoal;

typedef boost::shared_ptr< ::woosh_msgs::AutoDockActionGoal > AutoDockActionGoalPtr;
typedef boost::shared_ptr< ::woosh_msgs::AutoDockActionGoal const> AutoDockActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4277d51816f3494d9c2cdbccfd5e880";
  }

  static const char* value(const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4277d51816f3494ULL;
  static const uint64_t static_value2 = 0xd9c2cdbccfd5e880ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/AutoDockActionGoal";
  }

  static const char* value(const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"AutoDockGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/AutoDockGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string  tag_no  #tag编号\n"
"\n"
"int32   type\n"
"int32   START = 0\n"
"int32   PAUSE = 1\n"
"int32   RESUM = 2\n"
"int32   LEAVE = 3\n"
"int32   RESET = 4\n"
"\n"
"int32   lift_type\n"
"int32   UP = 0\n"
"int32   DOWN = 1\n"
"\n"
"float32 leave_distance  #-999\n"
"geometry_msgs/Pose2D  targetPose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDockActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::AutoDockActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::woosh_msgs::AutoDockGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_AUTODOCKACTIONGOAL_H
