// Generated by gencpp from file woosh_msgs/ChargeControlFeedback.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_CHARGECONTROLFEEDBACK_H
#define WOOSH_MSGS_MESSAGE_CHARGECONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct ChargeControlFeedback_
{
  typedef ChargeControlFeedback_<ContainerAllocator> Type;

  ChargeControlFeedback_()
    : feedback(0)
    , executeMode(0)  {
    }
  ChargeControlFeedback_(const ContainerAllocator& _alloc)
    : feedback(0)
    , executeMode(0)  {
  (void)_alloc;
    }



   typedef int8_t _feedback_type;
  _feedback_type feedback;

   typedef uint8_t _executeMode_type;
  _executeMode_type executeMode;





  typedef boost::shared_ptr< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ChargeControlFeedback_

typedef ::woosh_msgs::ChargeControlFeedback_<std::allocator<void> > ChargeControlFeedback;

typedef boost::shared_ptr< ::woosh_msgs::ChargeControlFeedback > ChargeControlFeedbackPtr;
typedef boost::shared_ptr< ::woosh_msgs::ChargeControlFeedback const> ChargeControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator1> & lhs, const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback &&
    lhs.executeMode == rhs.executeMode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator1> & lhs, const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4046d8eceb4c4136d262ce19164fb6f7";
  }

  static const char* value(const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4046d8eceb4c4136ULL;
  static const uint64_t static_value2 = 0xd262ce19164fb6f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/ChargeControlFeedback";
  }

  static const char* value(const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 feedback\n"
"uint8 executeMode\n"
"\n"
;
  }

  static const char* value(const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
      stream.next(m.executeMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargeControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::ChargeControlFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int8_t>::stream(s, indent + "  ", v.feedback);
    s << indent << "executeMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.executeMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_CHARGECONTROLFEEDBACK_H
