// Generated by gencpp from file woosh_msgs/DeploymentRequest.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_DEPLOYMENTREQUEST_H
#define WOOSH_MSGS_MESSAGE_DEPLOYMENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct DeploymentRequest_
{
  typedef DeploymentRequest_<ContainerAllocator> Type;

  DeploymentRequest_()
    : type(0)
    , mode(0)  {
    }
  DeploymentRequest_(const ContainerAllocator& _alloc)
    : type(0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef int8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeploymentRequest_

typedef ::woosh_msgs::DeploymentRequest_<std::allocator<void> > DeploymentRequest;

typedef boost::shared_ptr< ::woosh_msgs::DeploymentRequest > DeploymentRequestPtr;
typedef boost::shared_ptr< ::woosh_msgs::DeploymentRequest const> DeploymentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::DeploymentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::DeploymentRequest_<ContainerAllocator1> & lhs, const ::woosh_msgs::DeploymentRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::DeploymentRequest_<ContainerAllocator1> & lhs, const ::woosh_msgs::DeploymentRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9e2945a6922bafcd9fd114e002c6a80";
  }

  static const char* value(const ::woosh_msgs::DeploymentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9e2945a6922bafcULL;
  static const uint64_t static_value2 = 0xd9fd114e002c6a80ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/DeploymentRequest";
  }

  static const char* value(const ::woosh_msgs::DeploymentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 type   #0:beacons  1:ar_tag  2:reflector\n"
"int8 mode   #0:开始采集  1:取消采集（beacons多组数据生效）  2:reflector校验\n"
;
  }

  static const char* value(const ::woosh_msgs::DeploymentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeploymentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::DeploymentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::DeploymentRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_DEPLOYMENTREQUEST_H
