// Generated by gencpp from file woosh_msgs/DeploymentResponse.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_DEPLOYMENTRESPONSE_H
#define WOOSH_MSGS_MESSAGE_DEPLOYMENTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <woosh_msgs/deployment_markers.h>
#include <woosh_msgs/reflector_errorID_group.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct DeploymentResponse_
{
  typedef DeploymentResponse_<ContainerAllocator> Type;

  DeploymentResponse_()
    : success(false)
    , message()
    , point1Valid(false)
    , point2Valid(false)
    , point3Valid(false)
    , collectedNumber(0)
    , numberOfFailBeacons(0)
    , markers()
    , reflector_errorID_groups()  {
    }
  DeploymentResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , point1Valid(false)
    , point2Valid(false)
    , point3Valid(false)
    , collectedNumber(0)
    , numberOfFailBeacons(0)
    , markers(_alloc)
    , reflector_errorID_groups(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef uint8_t _point1Valid_type;
  _point1Valid_type point1Valid;

   typedef uint8_t _point2Valid_type;
  _point2Valid_type point2Valid;

   typedef uint8_t _point3Valid_type;
  _point3Valid_type point3Valid;

   typedef uint8_t _collectedNumber_type;
  _collectedNumber_type collectedNumber;

   typedef int8_t _numberOfFailBeacons_type;
  _numberOfFailBeacons_type numberOfFailBeacons;

   typedef  ::woosh_msgs::deployment_markers_<ContainerAllocator>  _markers_type;
  _markers_type markers;

   typedef std::vector< ::woosh_msgs::reflector_errorID_group_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::woosh_msgs::reflector_errorID_group_<ContainerAllocator> >> _reflector_errorID_groups_type;
  _reflector_errorID_groups_type reflector_errorID_groups;





  typedef boost::shared_ptr< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DeploymentResponse_

typedef ::woosh_msgs::DeploymentResponse_<std::allocator<void> > DeploymentResponse;

typedef boost::shared_ptr< ::woosh_msgs::DeploymentResponse > DeploymentResponsePtr;
typedef boost::shared_ptr< ::woosh_msgs::DeploymentResponse const> DeploymentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::DeploymentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::DeploymentResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::DeploymentResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.point1Valid == rhs.point1Valid &&
    lhs.point2Valid == rhs.point2Valid &&
    lhs.point3Valid == rhs.point3Valid &&
    lhs.collectedNumber == rhs.collectedNumber &&
    lhs.numberOfFailBeacons == rhs.numberOfFailBeacons &&
    lhs.markers == rhs.markers &&
    lhs.reflector_errorID_groups == rhs.reflector_errorID_groups;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::DeploymentResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::DeploymentResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "041a6fb2f9dc6c2f664d067e2b4b5e09";
  }

  static const char* value(const ::woosh_msgs::DeploymentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x041a6fb2f9dc6c2fULL;
  static const uint64_t static_value2 = 0x664d067e2b4b5e09ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/DeploymentResponse";
  }

  static const char* value(const ::woosh_msgs::DeploymentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success   # indicate successful run of triggered service\n"
"string message # informational, e.g. for error messages\n"
"bool point1Valid\n"
"bool point2Valid\n"
"bool point3Valid\n"
"uint8 collectedNumber       #表示此时已经收集几个数据了（总共需要三个）\n"
"int8 numberOfFailBeacons     #三次采集后未发布的uwb基站数\n"
"\n"
"deployment_markers markers  #基于map坐标系\n"
"\n"
"reflector_errorID_group[] reflector_errorID_groups\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/deployment_markers\n"
"Header header\n"
"deployment_marker[] markers\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/deployment_marker\n"
"uint32 markerID\n"
"geometry_msgs/Pose pose\n"
"uint16  group\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/reflector_errorID_group\n"
"reflector_errorID[] reflector_errorIDs\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/reflector_errorID\n"
"uint32 ID1\n"
"uint32 ID2\n"
"uint32 ID3\n"
;
  }

  static const char* value(const ::woosh_msgs::DeploymentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.point1Valid);
      stream.next(m.point2Valid);
      stream.next(m.point3Valid);
      stream.next(m.collectedNumber);
      stream.next(m.numberOfFailBeacons);
      stream.next(m.markers);
      stream.next(m.reflector_errorID_groups);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeploymentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::DeploymentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::DeploymentResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "point1Valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.point1Valid);
    s << indent << "point2Valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.point2Valid);
    s << indent << "point3Valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.point3Valid);
    s << indent << "collectedNumber: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collectedNumber);
    s << indent << "numberOfFailBeacons: ";
    Printer<int8_t>::stream(s, indent + "  ", v.numberOfFailBeacons);
    s << indent << "markers: ";
    s << std::endl;
    Printer< ::woosh_msgs::deployment_markers_<ContainerAllocator> >::stream(s, indent + "  ", v.markers);
    s << indent << "reflector_errorID_groups[]" << std::endl;
    for (size_t i = 0; i < v.reflector_errorID_groups.size(); ++i)
    {
      s << indent << "  reflector_errorID_groups[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::woosh_msgs::reflector_errorID_group_<ContainerAllocator> >::stream(s, indent + "    ", v.reflector_errorID_groups[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_DEPLOYMENTRESPONSE_H
