// Generated by gencpp from file woosh_msgs/DriverFreeResponse.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_DRIVERFREERESPONSE_H
#define WOOSH_MSGS_MESSAGE_DRIVERFREERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct DriverFreeResponse_
{
  typedef DriverFreeResponse_<ContainerAllocator> Type;

  DriverFreeResponse_()
    : status(false)
    , success(false)
    , message()  {
    }
  DriverFreeResponse_(const ContainerAllocator& _alloc)
    : status(false)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DriverFreeResponse_

typedef ::woosh_msgs::DriverFreeResponse_<std::allocator<void> > DriverFreeResponse;

typedef boost::shared_ptr< ::woosh_msgs::DriverFreeResponse > DriverFreeResponsePtr;
typedef boost::shared_ptr< ::woosh_msgs::DriverFreeResponse const> DriverFreeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "129336dda71243273edca62ed7de3869";
  }

  static const char* value(const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x129336dda7124327ULL;
  static const uint64_t static_value2 = 0x3edca62ed7de3869ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/DriverFreeResponse";
  }

  static const char* value(const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"bool success\n"
"string message\n"
;
  }

  static const char* value(const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriverFreeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::DriverFreeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::DriverFreeResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_DRIVERFREERESPONSE_H
