// Generated by gencpp from file woosh_msgs/DriverFree.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_DRIVERFREE_H
#define WOOSH_MSGS_MESSAGE_DRIVERFREE_H

#include <ros/service_traits.h>


#include <woosh_msgs/DriverFreeRequest.h>
#include <woosh_msgs/DriverFreeResponse.h>


namespace woosh_msgs
{

struct DriverFree
{

typedef DriverFreeRequest Request;
typedef DriverFreeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriverFree
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::DriverFree > {
  static const char* value()
  {
    return "a0ef03ec75775620626a8ace8290514a";
  }

  static const char* value(const ::woosh_msgs::DriverFree&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::DriverFree > {
  static const char* value()
  {
    return "woosh_msgs/DriverFree";
  }

  static const char* value(const ::woosh_msgs::DriverFree&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::DriverFreeRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::DriverFree >
template<>
struct MD5Sum< ::woosh_msgs::DriverFreeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::DriverFree >::value();
  }
  static const char* value(const ::woosh_msgs::DriverFreeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::DriverFreeRequest> should match
// service_traits::DataType< ::woosh_msgs::DriverFree >
template<>
struct DataType< ::woosh_msgs::DriverFreeRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::DriverFree >::value();
  }
  static const char* value(const ::woosh_msgs::DriverFreeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::DriverFreeResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::DriverFree >
template<>
struct MD5Sum< ::woosh_msgs::DriverFreeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::DriverFree >::value();
  }
  static const char* value(const ::woosh_msgs::DriverFreeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::DriverFreeResponse> should match
// service_traits::DataType< ::woosh_msgs::DriverFree >
template<>
struct DataType< ::woosh_msgs::DriverFreeResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::DriverFree >::value();
  }
  static const char* value(const ::woosh_msgs::DriverFreeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_DRIVERFREE_H
