// Generated by gencpp from file woosh_msgs/EnableHotSpotResponse.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_ENABLEHOTSPOTRESPONSE_H
#define WOOSH_MSGS_MESSAGE_ENABLEHOTSPOTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct EnableHotSpotResponse_
{
  typedef EnableHotSpotResponse_<ContainerAllocator> Type;

  EnableHotSpotResponse_()
    : status(0)
    , message()  {
    }
  EnableHotSpotResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EnableHotSpotResponse_

typedef ::woosh_msgs::EnableHotSpotResponse_<std::allocator<void> > EnableHotSpotResponse;

typedef boost::shared_ptr< ::woosh_msgs::EnableHotSpotResponse > EnableHotSpotResponsePtr;
typedef boost::shared_ptr< ::woosh_msgs::EnableHotSpotResponse const> EnableHotSpotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator1> & lhs, const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c1d00fb8b4e78420f43d93d5292a429";
  }

  static const char* value(const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c1d00fb8b4e7842ULL;
  static const uint64_t static_value2 = 0x0f43d93d5292a429ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/EnableHotSpotResponse";
  }

  static const char* value(const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableHotSpotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::EnableHotSpotResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_ENABLEHOTSPOTRESPONSE_H
