// Generated by gencpp from file woosh_msgs/ExecTaskRequest.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_EXECTASKREQUEST_H
#define WOOSH_MSGS_MESSAGE_EXECTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct ExecTaskRequest_
{
  typedef ExecTaskRequest_<ContainerAllocator> Type;

  ExecTaskRequest_()
    : task_exect(0)
    , task_id(0)
    , task_type(0)
    , direction(0)
    , task_type_no(0)
    , mark_no()
    , poses()
    , custom(0)  {
    }
  ExecTaskRequest_(const ContainerAllocator& _alloc)
    : task_exect(0)
    , task_id(0)
    , task_type(0)
    , direction(0)
    , task_type_no(0)
    , mark_no(_alloc)
    , poses(_alloc)
    , custom(0)  {
  (void)_alloc;
    }



   typedef uint8_t _task_exect_type;
  _task_exect_type task_exect;

   typedef int64_t _task_id_type;
  _task_id_type task_id;

   typedef uint8_t _task_type_type;
  _task_type_type task_type;

   typedef uint8_t _direction_type;
  _direction_type direction;

   typedef uint32_t _task_type_no_type;
  _task_type_no_type task_type_no;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mark_no_type;
  _mark_no_type mark_no;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _poses_type;
  _poses_type poses;

   typedef int8_t _custom_type;
  _custom_type custom;





  typedef boost::shared_ptr< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecTaskRequest_

typedef ::woosh_msgs::ExecTaskRequest_<std::allocator<void> > ExecTaskRequest;

typedef boost::shared_ptr< ::woosh_msgs::ExecTaskRequest > ExecTaskRequestPtr;
typedef boost::shared_ptr< ::woosh_msgs::ExecTaskRequest const> ExecTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator1> & lhs, const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task_exect == rhs.task_exect &&
    lhs.task_id == rhs.task_id &&
    lhs.task_type == rhs.task_type &&
    lhs.direction == rhs.direction &&
    lhs.task_type_no == rhs.task_type_no &&
    lhs.mark_no == rhs.mark_no &&
    lhs.poses == rhs.poses &&
    lhs.custom == rhs.custom;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator1> & lhs, const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d13f36fcb97fa2e9e5a8a379bd4a1415";
  }

  static const char* value(const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd13f36fcb97fa2e9ULL;
  static const uint64_t static_value2 = 0xe5a8a379bd4a1415ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/ExecTaskRequest";
  }

  static const char* value(const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 task_exect      #任务执行请求，1： 执行，2：暂停，3： 继续， 4：取消, 6:等待打断\n"
"int64 task_id         #任务ID\n"
"uint8 task_type       #任务类型, 1: 拣选 2：泊车 3： 充电  4： 搬运\n"
"uint8 direction       #动作方向, 0： 未定义 1： 上料  2：下料, 不是上下料任务填0，可选项\n"
"uint32 task_type_no   #类型组合,默认0，自定义，可选项\n"
"string mark_no        #目标点（储位）编号，如果填写编号，则 任务路经项 可以不用填写，若要填写,任务路经的最后一个点，必须和此储位点一致\n"
"geometry_msgs/PoseStamped[] poses #任务路经，如果是一个点（目标点），则表示由系统自己规划，最总到达此目标点，可选项\n"
"byte custom           # 自定义字段，因项目而异，可选项\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_exect);
      stream.next(m.task_id);
      stream.next(m.task_type);
      stream.next(m.direction);
      stream.next(m.task_type_no);
      stream.next(m.mark_no);
      stream.next(m.poses);
      stream.next(m.custom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::ExecTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::ExecTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task_exect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_exect);
    s << indent << "task_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "task_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_type);
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "task_type_no: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task_type_no);
    s << indent << "mark_no: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mark_no);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "custom: ";
    Printer<int8_t>::stream(s, indent + "  ", v.custom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_EXECTASKREQUEST_H
