// Generated by gencpp from file woosh_msgs/Field.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_FIELD_H
#define WOOSH_MSGS_MESSAGE_FIELD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <woosh_msgs/NavFieldPoint.h>
#include <woosh_msgs/NavFieldPoint.h>
#include <woosh_msgs/NavFieldPoint.h>
#include <woosh_msgs/NavFieldPoint.h>
#include <woosh_msgs/NavFieldPoint.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct Field_
{
  typedef Field_<ContainerAllocator> Type;

  Field_()
    : id(0)
    , type(0)
    , slope_angle(0.0)
    , slope_arrow()
    , capacity(0)
    , wait_time_out(0.0)
    , nav_mode(0)
    , max_speed(0.0)
    , direction(0)
    , radius(0.0)
    , offset(0.0)
    , vertex()
    , nav_pos()
    , entry()
    , extrance()  {
    }
  Field_(const ContainerAllocator& _alloc)
    : id(0)
    , type(0)
    , slope_angle(0.0)
    , slope_arrow(_alloc)
    , capacity(0)
    , wait_time_out(0.0)
    , nav_mode(0)
    , max_speed(0.0)
    , direction(0)
    , radius(0.0)
    , offset(0.0)
    , vertex(_alloc)
    , nav_pos(_alloc)
    , entry(_alloc)
    , extrance(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef int32_t _type_type;
  _type_type type;

   typedef float _slope_angle_type;
  _slope_angle_type slope_angle;

   typedef  ::woosh_msgs::NavFieldPoint_<ContainerAllocator>  _slope_arrow_type;
  _slope_arrow_type slope_arrow;

   typedef int32_t _capacity_type;
  _capacity_type capacity;

   typedef float _wait_time_out_type;
  _wait_time_out_type wait_time_out;

   typedef int32_t _nav_mode_type;
  _nav_mode_type nav_mode;

   typedef float _max_speed_type;
  _max_speed_type max_speed;

   typedef int32_t _direction_type;
  _direction_type direction;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _offset_type;
  _offset_type offset;

   typedef std::vector< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> >> _vertex_type;
  _vertex_type vertex;

   typedef std::vector< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> >> _nav_pos_type;
  _nav_pos_type nav_pos;

   typedef  ::woosh_msgs::NavFieldPoint_<ContainerAllocator>  _entry_type;
  _entry_type entry;

   typedef  ::woosh_msgs::NavFieldPoint_<ContainerAllocator>  _extrance_type;
  _extrance_type extrance;





  typedef boost::shared_ptr< ::woosh_msgs::Field_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::Field_<ContainerAllocator> const> ConstPtr;

}; // struct Field_

typedef ::woosh_msgs::Field_<std::allocator<void> > Field;

typedef boost::shared_ptr< ::woosh_msgs::Field > FieldPtr;
typedef boost::shared_ptr< ::woosh_msgs::Field const> FieldConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::Field_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::Field_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::Field_<ContainerAllocator1> & lhs, const ::woosh_msgs::Field_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.slope_angle == rhs.slope_angle &&
    lhs.slope_arrow == rhs.slope_arrow &&
    lhs.capacity == rhs.capacity &&
    lhs.wait_time_out == rhs.wait_time_out &&
    lhs.nav_mode == rhs.nav_mode &&
    lhs.max_speed == rhs.max_speed &&
    lhs.direction == rhs.direction &&
    lhs.radius == rhs.radius &&
    lhs.offset == rhs.offset &&
    lhs.vertex == rhs.vertex &&
    lhs.nav_pos == rhs.nav_pos &&
    lhs.entry == rhs.entry &&
    lhs.extrance == rhs.extrance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::Field_<ContainerAllocator1> & lhs, const ::woosh_msgs::Field_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::Field_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::Field_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::Field_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::Field_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::Field_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::Field_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::Field_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd1f433a6719ae3939066ca26b7c7b36";
  }

  static const char* value(const ::woosh_msgs::Field_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd1f433a6719ae39ULL;
  static const uint64_t static_value2 = 0x39066ca26b7c7b36ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::Field_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/Field";
  }

  static const char* value(const ::woosh_msgs::Field_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::Field_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id		#通道id\n"
"int32 type		#通道类型, 双行道=0,单行道=1,单向道=2,路口=3, 狭窄通道=4,定位域=5,爬坡域=6,Odom域=7\n"
"float32 slope_angle 	#爬坡域角度\n"
"NavFieldPoint slope_arrow   #爬坡域箭头位姿\n"
"int32 capacity		#通道容量\n"
"float32 wait_time_out	#停等超时模式下的超时时间\n"
"int32 nav_mode		#导航模式,模糊避让=0,精准避让=1,停等=2,停等超时=3, 狭窄通道=10, 磁条导航=11, 二维码导航=12\n"
"float32 max_speed		#通道最高速度,设为0,则不约束最高速度,非0则以设定的速度为机器人在该通道的最高速度\n"
"int32 direction		#单向道的方向\n"
"float32 radius  #半径\n"
"float32 offset  # 偏移\n"
"NavFieldPoint[] vertex	#域顶点\n"
"NavFieldPoint[] nav_pos	#域中引导点数组,单向道中引导点的存储顺序决定其方向，数组里点的id有效\n"
"NavFieldPoint entry	#单向道入口\n"
"NavFieldPoint extrance	#单向道出口\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/NavFieldPoint\n"
"geometry_msgs/Point pt	#Marker position\n"
"uint32 id 		#Marker id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::woosh_msgs::Field_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::Field_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.slope_angle);
      stream.next(m.slope_arrow);
      stream.next(m.capacity);
      stream.next(m.wait_time_out);
      stream.next(m.nav_mode);
      stream.next(m.max_speed);
      stream.next(m.direction);
      stream.next(m.radius);
      stream.next(m.offset);
      stream.next(m.vertex);
      stream.next(m.nav_pos);
      stream.next(m.entry);
      stream.next(m.extrance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Field_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::Field_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::Field_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "slope_angle: ";
    Printer<float>::stream(s, indent + "  ", v.slope_angle);
    s << indent << "slope_arrow: ";
    s << std::endl;
    Printer< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.slope_arrow);
    s << indent << "capacity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.capacity);
    s << indent << "wait_time_out: ";
    Printer<float>::stream(s, indent + "  ", v.wait_time_out);
    s << indent << "nav_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nav_mode);
    s << indent << "max_speed: ";
    Printer<float>::stream(s, indent + "  ", v.max_speed);
    s << indent << "direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direction);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "offset: ";
    Printer<float>::stream(s, indent + "  ", v.offset);
    s << indent << "vertex[]" << std::endl;
    for (size_t i = 0; i < v.vertex.size(); ++i)
    {
      s << indent << "  vertex[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.vertex[i]);
    }
    s << indent << "nav_pos[]" << std::endl;
    for (size_t i = 0; i < v.nav_pos.size(); ++i)
    {
      s << indent << "  nav_pos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.nav_pos[i]);
    }
    s << indent << "entry: ";
    s << std::endl;
    Printer< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.entry);
    s << indent << "extrance: ";
    s << std::endl;
    Printer< ::woosh_msgs::NavFieldPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.extrance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_FIELD_H
