// Generated by gencpp from file woosh_msgs/FollowCtlRequest.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_FOLLOWCTLREQUEST_H
#define WOOSH_MSGS_MESSAGE_FOLLOWCTLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct FollowCtlRequest_
{
  typedef FollowCtlRequest_<ContainerAllocator> Type;

  FollowCtlRequest_()
    : function(0)
    , command(0)
    , message()  {
    }
  FollowCtlRequest_(const ContainerAllocator& _alloc)
    : function(0)
    , command(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _function_type;
  _function_type function;

   typedef int32_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FollowCtlRequest_

typedef ::woosh_msgs::FollowCtlRequest_<std::allocator<void> > FollowCtlRequest;

typedef boost::shared_ptr< ::woosh_msgs::FollowCtlRequest > FollowCtlRequestPtr;
typedef boost::shared_ptr< ::woosh_msgs::FollowCtlRequest const> FollowCtlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator1> & lhs, const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.function == rhs.function &&
    lhs.command == rhs.command &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator1> & lhs, const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98afd5da7b8af42c5431383dd873e3e5";
  }

  static const char* value(const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98afd5da7b8af42cULL;
  static const uint64_t static_value2 = 0x5431383dd873e3e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/FollowCtlRequest";
  }

  static const char* value(const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 function\n"
"int32 command\n"
"string message\n"
;
  }

  static const char* value(const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.function);
      stream.next(m.command);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowCtlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::FollowCtlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::FollowCtlRequest_<ContainerAllocator>& v)
  {
    s << indent << "function: ";
    Printer<int32_t>::stream(s, indent + "  ", v.function);
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_FOLLOWCTLREQUEST_H
