// Generated by gencpp from file woosh_msgs/FollowCtl.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_FOLLOWCTL_H
#define WOOSH_MSGS_MESSAGE_FOLLOWCTL_H

#include <ros/service_traits.h>


#include <woosh_msgs/FollowCtlRequest.h>
#include <woosh_msgs/FollowCtlResponse.h>


namespace woosh_msgs
{

struct FollowCtl
{

typedef FollowCtlRequest Request;
typedef FollowCtlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FollowCtl
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::FollowCtl > {
  static const char* value()
  {
    return "11f809d80e616065ce721fceb2f99c9f";
  }

  static const char* value(const ::woosh_msgs::FollowCtl&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::FollowCtl > {
  static const char* value()
  {
    return "woosh_msgs/FollowCtl";
  }

  static const char* value(const ::woosh_msgs::FollowCtl&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::FollowCtlRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::FollowCtl >
template<>
struct MD5Sum< ::woosh_msgs::FollowCtlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::FollowCtl >::value();
  }
  static const char* value(const ::woosh_msgs::FollowCtlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::FollowCtlRequest> should match
// service_traits::DataType< ::woosh_msgs::FollowCtl >
template<>
struct DataType< ::woosh_msgs::FollowCtlRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::FollowCtl >::value();
  }
  static const char* value(const ::woosh_msgs::FollowCtlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::FollowCtlResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::FollowCtl >
template<>
struct MD5Sum< ::woosh_msgs::FollowCtlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::FollowCtl >::value();
  }
  static const char* value(const ::woosh_msgs::FollowCtlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::FollowCtlResponse> should match
// service_traits::DataType< ::woosh_msgs::FollowCtl >
template<>
struct DataType< ::woosh_msgs::FollowCtlResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::FollowCtl >::value();
  }
  static const char* value(const ::woosh_msgs::FollowCtlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_FOLLOWCTL_H
