// Generated by gencpp from file woosh_msgs/GetAvailableWiFiList.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_GETAVAILABLEWIFILIST_H
#define WOOSH_MSGS_MESSAGE_GETAVAILABLEWIFILIST_H

#include <ros/service_traits.h>


#include <woosh_msgs/GetAvailableWiFiListRequest.h>
#include <woosh_msgs/GetAvailableWiFiListResponse.h>


namespace woosh_msgs
{

struct GetAvailableWiFiList
{

typedef GetAvailableWiFiListRequest Request;
typedef GetAvailableWiFiListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAvailableWiFiList
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::GetAvailableWiFiList > {
  static const char* value()
  {
    return "f05424b77a66a214dd3a93c8ea8e16bb";
  }

  static const char* value(const ::woosh_msgs::GetAvailableWiFiList&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::GetAvailableWiFiList > {
  static const char* value()
  {
    return "woosh_msgs/GetAvailableWiFiList";
  }

  static const char* value(const ::woosh_msgs::GetAvailableWiFiList&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::GetAvailableWiFiListRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::GetAvailableWiFiList >
template<>
struct MD5Sum< ::woosh_msgs::GetAvailableWiFiListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::GetAvailableWiFiList >::value();
  }
  static const char* value(const ::woosh_msgs::GetAvailableWiFiListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::GetAvailableWiFiListRequest> should match
// service_traits::DataType< ::woosh_msgs::GetAvailableWiFiList >
template<>
struct DataType< ::woosh_msgs::GetAvailableWiFiListRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::GetAvailableWiFiList >::value();
  }
  static const char* value(const ::woosh_msgs::GetAvailableWiFiListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::GetAvailableWiFiListResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::GetAvailableWiFiList >
template<>
struct MD5Sum< ::woosh_msgs::GetAvailableWiFiListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::GetAvailableWiFiList >::value();
  }
  static const char* value(const ::woosh_msgs::GetAvailableWiFiListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::GetAvailableWiFiListResponse> should match
// service_traits::DataType< ::woosh_msgs::GetAvailableWiFiList >
template<>
struct DataType< ::woosh_msgs::GetAvailableWiFiListResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::GetAvailableWiFiList >::value();
  }
  static const char* value(const ::woosh_msgs::GetAvailableWiFiListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_GETAVAILABLEWIFILIST_H
