// Generated by gencpp from file woosh_msgs/GetLastError.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_GETLASTERROR_H
#define WOOSH_MSGS_MESSAGE_GETLASTERROR_H

#include <ros/service_traits.h>


#include <woosh_msgs/GetLastErrorRequest.h>
#include <woosh_msgs/GetLastErrorResponse.h>


namespace woosh_msgs
{

struct GetLastError
{

typedef GetLastErrorRequest Request;
typedef GetLastErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLastError
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::GetLastError > {
  static const char* value()
  {
    return "b40afb2571e9bdb7a133903e7060837b";
  }

  static const char* value(const ::woosh_msgs::GetLastError&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::GetLastError > {
  static const char* value()
  {
    return "woosh_msgs/GetLastError";
  }

  static const char* value(const ::woosh_msgs::GetLastError&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::GetLastErrorRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::GetLastError >
template<>
struct MD5Sum< ::woosh_msgs::GetLastErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::GetLastError >::value();
  }
  static const char* value(const ::woosh_msgs::GetLastErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::GetLastErrorRequest> should match
// service_traits::DataType< ::woosh_msgs::GetLastError >
template<>
struct DataType< ::woosh_msgs::GetLastErrorRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::GetLastError >::value();
  }
  static const char* value(const ::woosh_msgs::GetLastErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::GetLastErrorResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::GetLastError >
template<>
struct MD5Sum< ::woosh_msgs::GetLastErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::GetLastError >::value();
  }
  static const char* value(const ::woosh_msgs::GetLastErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::GetLastErrorResponse> should match
// service_traits::DataType< ::woosh_msgs::GetLastError >
template<>
struct DataType< ::woosh_msgs::GetLastErrorResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::GetLastError >::value();
  }
  static const char* value(const ::woosh_msgs::GetLastErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_GETLASTERROR_H
