// Generated by gencpp from file woosh_msgs/InitPose.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_INITPOSE_H
#define WOOSH_MSGS_MESSAGE_INITPOSE_H

#include <ros/service_traits.h>


#include <woosh_msgs/InitPoseRequest.h>
#include <woosh_msgs/InitPoseResponse.h>


namespace woosh_msgs
{

struct InitPose
{

typedef InitPoseRequest Request;
typedef InitPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitPose
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::InitPose > {
  static const char* value()
  {
    return "d85ac5803be8daa00e52d453ae42eb7d";
  }

  static const char* value(const ::woosh_msgs::InitPose&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::InitPose > {
  static const char* value()
  {
    return "woosh_msgs/InitPose";
  }

  static const char* value(const ::woosh_msgs::InitPose&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::InitPoseRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::InitPose >
template<>
struct MD5Sum< ::woosh_msgs::InitPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::InitPose >::value();
  }
  static const char* value(const ::woosh_msgs::InitPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::InitPoseRequest> should match
// service_traits::DataType< ::woosh_msgs::InitPose >
template<>
struct DataType< ::woosh_msgs::InitPoseRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::InitPose >::value();
  }
  static const char* value(const ::woosh_msgs::InitPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::InitPoseResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::InitPose >
template<>
struct MD5Sum< ::woosh_msgs::InitPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::InitPose >::value();
  }
  static const char* value(const ::woosh_msgs::InitPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::InitPoseResponse> should match
// service_traits::DataType< ::woosh_msgs::InitPose >
template<>
struct DataType< ::woosh_msgs::InitPoseResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::InitPose >::value();
  }
  static const char* value(const ::woosh_msgs::InitPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_INITPOSE_H
