// Generated by gencpp from file woosh_msgs/IO.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_IO_H
#define WOOSH_MSGS_MESSAGE_IO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct IO_
{
  typedef IO_<ContainerAllocator> Type;

  IO_()
    : header()
    , module(0)
    , submodule(0)
    , id(0)
    , status(0)  {
    }
  IO_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , module(0)
    , submodule(0)
    , id(0)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _module_type;
  _module_type module;

   typedef uint8_t _submodule_type;
  _submodule_type submodule;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::woosh_msgs::IO_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::IO_<ContainerAllocator> const> ConstPtr;

}; // struct IO_

typedef ::woosh_msgs::IO_<std::allocator<void> > IO;

typedef boost::shared_ptr< ::woosh_msgs::IO > IOPtr;
typedef boost::shared_ptr< ::woosh_msgs::IO const> IOConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::IO_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::IO_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::IO_<ContainerAllocator1> & lhs, const ::woosh_msgs::IO_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.module == rhs.module &&
    lhs.submodule == rhs.submodule &&
    lhs.id == rhs.id &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::IO_<ContainerAllocator1> & lhs, const ::woosh_msgs::IO_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::IO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::IO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::IO_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::IO_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::IO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::IO_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::IO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe404ac7c7eb28cb42b5db91b2ae3963";
  }

  static const char* value(const ::woosh_msgs::IO_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe404ac7c7eb28cbULL;
  static const uint64_t static_value2 = 0x42b5db91b2ae3963ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::IO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/IO";
  }

  static const char* value(const ::woosh_msgs::IO_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::IO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 module\n"
"uint8 submodule\n"
"uint8 id\n"
"uint8 status\n"
"\n"
"#channel and IO\n"
"#0x01 movebase key\n"
"#0x02 motor\n"
"#0x03 alarm  0.Beep 1.red 2.yellow 3.green 4.laser\n"
"#0x81 photoelec\n"
"\n"
"#status\n"
"#0 default\n"
"#1 trigger\n"
"#2 stop\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::woosh_msgs::IO_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::IO_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.module);
      stream.next(m.submodule);
      stream.next(m.id);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IO_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::IO_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::IO_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "module: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.module);
    s << indent << "submodule: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.submodule);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_IO_H
