// Generated by gencpp from file woosh_msgs/IOModuleControl.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_IOMODULECONTROL_H
#define WOOSH_MSGS_MESSAGE_IOMODULECONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct IOModuleControl_
{
  typedef IOModuleControl_<ContainerAllocator> Type;

  IOModuleControl_()
    : mode(0)
    , module(0)
    , submodule(0)
    , mask(0)  {
    }
  IOModuleControl_(const ContainerAllocator& _alloc)
    : mode(0)
    , module(0)
    , submodule(0)
    , mask(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _module_type;
  _module_type module;

   typedef uint8_t _submodule_type;
  _submodule_type submodule;

   typedef uint32_t _mask_type;
  _mask_type mask;





  typedef boost::shared_ptr< ::woosh_msgs::IOModuleControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::IOModuleControl_<ContainerAllocator> const> ConstPtr;

}; // struct IOModuleControl_

typedef ::woosh_msgs::IOModuleControl_<std::allocator<void> > IOModuleControl;

typedef boost::shared_ptr< ::woosh_msgs::IOModuleControl > IOModuleControlPtr;
typedef boost::shared_ptr< ::woosh_msgs::IOModuleControl const> IOModuleControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::IOModuleControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::IOModuleControl_<ContainerAllocator1> & lhs, const ::woosh_msgs::IOModuleControl_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.module == rhs.module &&
    lhs.submodule == rhs.submodule &&
    lhs.mask == rhs.mask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::IOModuleControl_<ContainerAllocator1> & lhs, const ::woosh_msgs::IOModuleControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::IOModuleControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::IOModuleControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::IOModuleControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aca0fa9fb5a15d009a37810bb307efcb";
  }

  static const char* value(const ::woosh_msgs::IOModuleControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaca0fa9fb5a15d00ULL;
  static const uint64_t static_value2 = 0x9a37810bb307efcbULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/IOModuleControl";
  }

  static const char* value(const ::woosh_msgs::IOModuleControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
"uint8 module\n"
"uint8 submodule\n"
"uint32 mask\n"
;
  }

  static const char* value(const ::woosh_msgs::IOModuleControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.module);
      stream.next(m.submodule);
      stream.next(m.mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IOModuleControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::IOModuleControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::IOModuleControl_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "module: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.module);
    s << indent << "submodule: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.submodule);
    s << indent << "mask: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_IOMODULECONTROL_H
