// Generated by gencpp from file woosh_msgs/LiftControl3Goal.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_LIFTCONTROL3GOAL_H
#define WOOSH_MSGS_MESSAGE_LIFTCONTROL3GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct LiftControl3Goal_
{
  typedef LiftControl3Goal_<ContainerAllocator> Type;

  LiftControl3Goal_()
    : mode(0)
    , execmode(0)
    , speed(0.0)
    , height(0.0)  {
    }
  LiftControl3Goal_(const ContainerAllocator& _alloc)
    : mode(0)
    , execmode(0)
    , speed(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _execmode_type;
  _execmode_type execmode;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _height_type;
  _height_type height;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CANCEL)
  #undef CANCEL
#endif
#if defined(_WIN32) && defined(EXCUTE)
  #undef EXCUTE
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(RESUM)
  #undef RESUM
#endif
#if defined(_WIN32) && defined(EXEC_QUERY)
  #undef EXEC_QUERY
#endif
#if defined(_WIN32) && defined(EXEC_ABSOLUTE)
  #undef EXEC_ABSOLUTE
#endif
#if defined(_WIN32) && defined(EXEC_RELATIVE)
  #undef EXEC_RELATIVE
#endif
#if defined(_WIN32) && defined(EXEC_CALIBRATION)
  #undef EXEC_CALIBRATION
#endif
#if defined(_WIN32) && defined(EXEC_TESTMODE)
  #undef EXEC_TESTMODE
#endif

  enum {
    CANCEL = 0u,
    EXCUTE = 1u,
    PAUSE = 2u,
    RESUM = 3u,
    EXEC_QUERY = 0u,
    EXEC_ABSOLUTE = 1u,
    EXEC_RELATIVE = 2u,
    EXEC_CALIBRATION = 3u,
    EXEC_TESTMODE = 5u,
  };


  typedef boost::shared_ptr< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> const> ConstPtr;

}; // struct LiftControl3Goal_

typedef ::woosh_msgs::LiftControl3Goal_<std::allocator<void> > LiftControl3Goal;

typedef boost::shared_ptr< ::woosh_msgs::LiftControl3Goal > LiftControl3GoalPtr;
typedef boost::shared_ptr< ::woosh_msgs::LiftControl3Goal const> LiftControl3GoalConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator1> & lhs, const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.execmode == rhs.execmode &&
    lhs.speed == rhs.speed &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator1> & lhs, const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1c19c7b7b8efaf2b601a6888f76cc1e";
  }

  static const char* value(const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1c19c7b7b8efaf2ULL;
  static const uint64_t static_value2 = 0xb601a6888f76cc1eULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/LiftControl3Goal";
  }

  static const char* value(const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 mode\n"
"uint8 execmode\n"
"float32 speed\n"
"float32 height\n"
"\n"
"#mode\n"
"uint8 CANCEL = 0\n"
"uint8 EXCUTE = 1\n"
"uint8 PAUSE = 2\n"
"uint8 RESUM = 3\n"
"\n"
"#execmode\n"
"uint8 EXEC_QUERY = 0 #查询状态\n"
"uint8 EXEC_ABSOLUTE = 1 #绝对位置\n"
"uint8 EXEC_RELATIVE = 2 #相对位置\n"
"uint8 EXEC_CALIBRATION = 3 #位置校准\n"
"uint8 EXEC_TESTMODE = 5 #测试模式\n"
;
  }

  static const char* value(const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.execmode);
      stream.next(m.speed);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftControl3Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::LiftControl3Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::LiftControl3Goal_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "execmode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execmode);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_LIFTCONTROL3GOAL_H
