// Generated by gencpp from file woosh_msgs/LiftControlResult.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_LIFTCONTROLRESULT_H
#define WOOSH_MSGS_MESSAGE_LIFTCONTROLRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct LiftControlResult_
{
  typedef LiftControlResult_<ContainerAllocator> Type;

  LiftControlResult_()
    : result(0)
    , executeMode(0)  {
    }
  LiftControlResult_(const ContainerAllocator& _alloc)
    : result(0)
    , executeMode(0)  {
  (void)_alloc;
    }



   typedef int8_t _result_type;
  _result_type result;

   typedef uint8_t _executeMode_type;
  _executeMode_type executeMode;





  typedef boost::shared_ptr< ::woosh_msgs::LiftControlResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::LiftControlResult_<ContainerAllocator> const> ConstPtr;

}; // struct LiftControlResult_

typedef ::woosh_msgs::LiftControlResult_<std::allocator<void> > LiftControlResult;

typedef boost::shared_ptr< ::woosh_msgs::LiftControlResult > LiftControlResultPtr;
typedef boost::shared_ptr< ::woosh_msgs::LiftControlResult const> LiftControlResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::LiftControlResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::LiftControlResult_<ContainerAllocator1> & lhs, const ::woosh_msgs::LiftControlResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.executeMode == rhs.executeMode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::LiftControlResult_<ContainerAllocator1> & lhs, const ::woosh_msgs::LiftControlResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::LiftControlResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::LiftControlResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::LiftControlResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bc59990f85b93635cae46a24ddcf90e";
  }

  static const char* value(const ::woosh_msgs::LiftControlResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bc59990f85b9363ULL;
  static const uint64_t static_value2 = 0x5cae46a24ddcf90eULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/LiftControlResult";
  }

  static const char* value(const ::woosh_msgs::LiftControlResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 result #1表示执行成功，负值表示执行失败\n"
"uint8 executeMode\n"
;
  }

  static const char* value(const ::woosh_msgs::LiftControlResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.executeMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftControlResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::LiftControlResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::LiftControlResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
    s << indent << "executeMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.executeMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_LIFTCONTROLRESULT_H
