// Generated by gencpp from file woosh_msgs/LiftControl2Result.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_LIFTCONTROL2RESULT_H
#define WOOSH_MSGS_MESSAGE_LIFTCONTROL2RESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct LiftControl2Result_
{
  typedef LiftControl2Result_<ContainerAllocator> Type;

  LiftControl2Result_()
    : result(0)
    , height(0.0)  {
    }
  LiftControl2Result_(const ContainerAllocator& _alloc)
    : result(0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _result_type;
  _result_type result;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> const> ConstPtr;

}; // struct LiftControl2Result_

typedef ::woosh_msgs::LiftControl2Result_<std::allocator<void> > LiftControl2Result;

typedef boost::shared_ptr< ::woosh_msgs::LiftControl2Result > LiftControl2ResultPtr;
typedef boost::shared_ptr< ::woosh_msgs::LiftControl2Result const> LiftControl2ResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::LiftControl2Result_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::LiftControl2Result_<ContainerAllocator1> & lhs, const ::woosh_msgs::LiftControl2Result_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::LiftControl2Result_<ContainerAllocator1> & lhs, const ::woosh_msgs::LiftControl2Result_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "212bb38d859a9cc54787b1535283c724";
  }

  static const char* value(const ::woosh_msgs::LiftControl2Result_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x212bb38d859a9cc5ULL;
  static const uint64_t static_value2 = 0x4787b1535283c724ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/LiftControl2Result";
  }

  static const char* value(const ::woosh_msgs::LiftControl2Result_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 result #1表示执行成功，负值表示执行失败\n"
"float32 height\n"
;
  }

  static const char* value(const ::woosh_msgs::LiftControl2Result_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftControl2Result_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::LiftControl2Result_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::LiftControl2Result_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_LIFTCONTROL2RESULT_H
