// Generated by gencpp from file woosh_msgs/RollerControlGoal.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_ROLLERCONTROLGOAL_H
#define WOOSH_MSGS_MESSAGE_ROLLERCONTROLGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct RollerControlGoal_
{
  typedef RollerControlGoal_<ContainerAllocator> Type;

  RollerControlGoal_()
    : mode(0)
    , executeMode(0)
    , connectMode(0)  {
    }
  RollerControlGoal_(const ContainerAllocator& _alloc)
    : mode(0)
    , executeMode(0)
    , connectMode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _executeMode_type;
  _executeMode_type executeMode;

   typedef uint8_t _connectMode_type;
  _connectMode_type connectMode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CANCEL)
  #undef CANCEL
#endif
#if defined(_WIN32) && defined(EXCUTE)
  #undef EXCUTE
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(RESUM)
  #undef RESUM
#endif
#if defined(_WIN32) && defined(FRONT_LOAD)
  #undef FRONT_LOAD
#endif
#if defined(_WIN32) && defined(FRONT_UNLOAD)
  #undef FRONT_UNLOAD
#endif
#if defined(_WIN32) && defined(BACK_LOAD)
  #undef BACK_LOAD
#endif
#if defined(_WIN32) && defined(BACK_UNLOAD)
  #undef BACK_UNLOAD
#endif
#if defined(_WIN32) && defined(NONE)
  #undef NONE
#endif
#if defined(_WIN32) && defined(CHECK)
  #undef CHECK
#endif
#if defined(_WIN32) && defined(PROCESSCTRL)
  #undef PROCESSCTRL
#endif

  enum {
    CANCEL = 0u,
    EXCUTE = 1u,
    PAUSE = 2u,
    RESUM = 3u,
    FRONT_LOAD = 1u,
    FRONT_UNLOAD = 2u,
    BACK_LOAD = 3u,
    BACK_UNLOAD = 4u,
    NONE = 0u,
    CHECK = 1u,
    PROCESSCTRL = 2u,
  };


  typedef boost::shared_ptr< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RollerControlGoal_

typedef ::woosh_msgs::RollerControlGoal_<std::allocator<void> > RollerControlGoal;

typedef boost::shared_ptr< ::woosh_msgs::RollerControlGoal > RollerControlGoalPtr;
typedef boost::shared_ptr< ::woosh_msgs::RollerControlGoal const> RollerControlGoalConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::RollerControlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::RollerControlGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::RollerControlGoal_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.executeMode == rhs.executeMode &&
    lhs.connectMode == rhs.connectMode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::RollerControlGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::RollerControlGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c052de08f3408efa27d6c5e9c0917c63";
  }

  static const char* value(const ::woosh_msgs::RollerControlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc052de08f3408efaULL;
  static const uint64_t static_value2 = 0x27d6c5e9c0917c63ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/RollerControlGoal";
  }

  static const char* value(const ::woosh_msgs::RollerControlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 mode\n"
"uint8 executeMode\n"
"uint8 connectMode\n"
"\n"
"#mode\n"
"uint8 CANCEL = 0\n"
"uint8 EXCUTE = 1\n"
"uint8 PAUSE = 2\n"
"uint8 RESUM = 3\n"
"\n"
"#executeMode\n"
"uint8 FRONT_LOAD = 1\n"
"uint8 FRONT_UNLOAD = 2\n"
"uint8 BACK_LOAD = 3\n"
"uint8 BACK_UNLOAD = 4\n"
"\n"
"#connectMode\n"
"uint8 NONE = 0\n"
"uint8 CHECK = 1\n"
"uint8 PROCESSCTRL = 2\n"
;
  }

  static const char* value(const ::woosh_msgs::RollerControlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.executeMode);
      stream.next(m.connectMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RollerControlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::RollerControlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::RollerControlGoal_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "executeMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.executeMode);
    s << indent << "connectMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connectMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_ROLLERCONTROLGOAL_H
