// Generated by gencpp from file woosh_msgs/RollerControlFeedback.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_ROLLERCONTROLFEEDBACK_H
#define WOOSH_MSGS_MESSAGE_ROLLERCONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct RollerControlFeedback_
{
  typedef RollerControlFeedback_<ContainerAllocator> Type;

  RollerControlFeedback_()
    : feedback(0)
    , executeMode(0)
    , feedbackSlave(0)  {
    }
  RollerControlFeedback_(const ContainerAllocator& _alloc)
    : feedback(0)
    , executeMode(0)
    , feedbackSlave(0)  {
  (void)_alloc;
    }



   typedef int8_t _feedback_type;
  _feedback_type feedback;

   typedef uint8_t _executeMode_type;
  _executeMode_type executeMode;

   typedef int8_t _feedbackSlave_type;
  _feedbackSlave_type feedbackSlave;





  typedef boost::shared_ptr< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RollerControlFeedback_

typedef ::woosh_msgs::RollerControlFeedback_<std::allocator<void> > RollerControlFeedback;

typedef boost::shared_ptr< ::woosh_msgs::RollerControlFeedback > RollerControlFeedbackPtr;
typedef boost::shared_ptr< ::woosh_msgs::RollerControlFeedback const> RollerControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator1> & lhs, const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback &&
    lhs.executeMode == rhs.executeMode &&
    lhs.feedbackSlave == rhs.feedbackSlave;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator1> & lhs, const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cc359b7e8bcabd40646986679a8f591";
  }

  static const char* value(const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cc359b7e8bcabd4ULL;
  static const uint64_t static_value2 = 0x0646986679a8f591ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/RollerControlFeedback";
  }

  static const char* value(const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 feedback\n"
"uint8 executeMode\n"
"int8 feedbackSlave\n"
"\n"
;
  }

  static const char* value(const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
      stream.next(m.executeMode);
      stream.next(m.feedbackSlave);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RollerControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::RollerControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::RollerControlFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int8_t>::stream(s, indent + "  ", v.feedback);
    s << indent << "executeMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.executeMode);
    s << indent << "feedbackSlave: ";
    Printer<int8_t>::stream(s, indent + "  ", v.feedbackSlave);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_ROLLERCONTROLFEEDBACK_H
