// Generated by gencpp from file woosh_msgs/SetMapServer.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_SETMAPSERVER_H
#define WOOSH_MSGS_MESSAGE_SETMAPSERVER_H

#include <ros/service_traits.h>


#include <woosh_msgs/SetMapServerRequest.h>
#include <woosh_msgs/SetMapServerResponse.h>


namespace woosh_msgs
{

struct SetMapServer
{

typedef SetMapServerRequest Request;
typedef SetMapServerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMapServer
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::SetMapServer > {
  static const char* value()
  {
    return "00ac068e4aec756233516c167301064c";
  }

  static const char* value(const ::woosh_msgs::SetMapServer&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::SetMapServer > {
  static const char* value()
  {
    return "woosh_msgs/SetMapServer";
  }

  static const char* value(const ::woosh_msgs::SetMapServer&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::SetMapServerRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::SetMapServer >
template<>
struct MD5Sum< ::woosh_msgs::SetMapServerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::SetMapServer >::value();
  }
  static const char* value(const ::woosh_msgs::SetMapServerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::SetMapServerRequest> should match
// service_traits::DataType< ::woosh_msgs::SetMapServer >
template<>
struct DataType< ::woosh_msgs::SetMapServerRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::SetMapServer >::value();
  }
  static const char* value(const ::woosh_msgs::SetMapServerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::SetMapServerResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::SetMapServer >
template<>
struct MD5Sum< ::woosh_msgs::SetMapServerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::SetMapServer >::value();
  }
  static const char* value(const ::woosh_msgs::SetMapServerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::SetMapServerResponse> should match
// service_traits::DataType< ::woosh_msgs::SetMapServer >
template<>
struct DataType< ::woosh_msgs::SetMapServerResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::SetMapServer >::value();
  }
  static const char* value(const ::woosh_msgs::SetMapServerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_SETMAPSERVER_H
