// Generated by gencpp from file woosh_msgs/StepControlAction.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_STEPCONTROLACTION_H
#define WOOSH_MSGS_MESSAGE_STEPCONTROLACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <woosh_msgs/StepControlActionGoal.h>
#include <woosh_msgs/StepControlActionResult.h>
#include <woosh_msgs/StepControlActionFeedback.h>

namespace woosh_msgs
{
template <class ContainerAllocator>
struct StepControlAction_
{
  typedef StepControlAction_<ContainerAllocator> Type;

  StepControlAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  StepControlAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::woosh_msgs::StepControlActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::woosh_msgs::StepControlActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::woosh_msgs::StepControlActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::woosh_msgs::StepControlAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::StepControlAction_<ContainerAllocator> const> ConstPtr;

}; // struct StepControlAction_

typedef ::woosh_msgs::StepControlAction_<std::allocator<void> > StepControlAction;

typedef boost::shared_ptr< ::woosh_msgs::StepControlAction > StepControlActionPtr;
typedef boost::shared_ptr< ::woosh_msgs::StepControlAction const> StepControlActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::StepControlAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::StepControlAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::StepControlAction_<ContainerAllocator1> & lhs, const ::woosh_msgs::StepControlAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::StepControlAction_<ContainerAllocator1> & lhs, const ::woosh_msgs::StepControlAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::StepControlAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::StepControlAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::StepControlAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49c1cde28227da312698a14f60348b90";
  }

  static const char* value(const ::woosh_msgs::StepControlAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49c1cde28227da31ULL;
  static const uint64_t static_value2 = 0x2698a14f60348b90ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/StepControlAction";
  }

  static const char* value(const ::woosh_msgs::StepControlAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"StepControlActionGoal action_goal\n"
"StepControlActionResult action_result\n"
"StepControlActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/StepControlActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"StepControlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/StepControlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 mode\n"
"bool useAvoid\n"
"StepControl[] stepControl\n"
"\n"
"#mode\n"
"uint8 CANCEL = 0\n"
"uint8 EXCUTE = 1\n"
"uint8 PAUSE = 2\n"
"uint8 RESUM = 3\n"
"\n"
"#stepControl.executeMode\n"
"uint8 STRAIGHT = 1 # 前行/后退\n"
"uint8 ROTATE = 2  #旋转\n"
"uint8 LATERAL = 3 #横向移动\n"
"uint8 DIAGONALIZE = 4 #斜向移动\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/StepControl\n"
"uint8 executeMode #1 表示X方向运动，2 表示旋转，3表示y方向运动，4表示斜向运动\n"
"float32 data      #运动的距离或者旋转角度\n"
"float32 speed     #运动的速度\n"
"float32 angle     # 斜向运动的角度\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/StepControlActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"StepControlResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/StepControlResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 result #1表示执行成功，负值表示执行失败\n"
"uint8 executeMode\n"
"float32 percent\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/StepControlActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"StepControlFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: woosh_msgs/StepControlFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 feedback\n"
"uint8 executeMode\n"
"float32 percent\n"
"\n"
;
  }

  static const char* value(const ::woosh_msgs::StepControlAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepControlAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::StepControlAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::StepControlAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::woosh_msgs::StepControlActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::woosh_msgs::StepControlActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::woosh_msgs::StepControlActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_STEPCONTROLACTION_H
