// Generated by gencpp from file woosh_msgs/StepCtrlAvoidObstacleFeedback.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_STEPCTRLAVOIDOBSTACLEFEEDBACK_H
#define WOOSH_MSGS_MESSAGE_STEPCTRLAVOIDOBSTACLEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct StepCtrlAvoidObstacleFeedback_
{
  typedef StepCtrlAvoidObstacleFeedback_<ContainerAllocator> Type;

  StepCtrlAvoidObstacleFeedback_()
    : obstacle_distance(0.0)  {
    }
  StepCtrlAvoidObstacleFeedback_(const ContainerAllocator& _alloc)
    : obstacle_distance(0.0)  {
  (void)_alloc;
    }



   typedef float _obstacle_distance_type;
  _obstacle_distance_type obstacle_distance;





  typedef boost::shared_ptr< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct StepCtrlAvoidObstacleFeedback_

typedef ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<std::allocator<void> > StepCtrlAvoidObstacleFeedback;

typedef boost::shared_ptr< ::woosh_msgs::StepCtrlAvoidObstacleFeedback > StepCtrlAvoidObstacleFeedbackPtr;
typedef boost::shared_ptr< ::woosh_msgs::StepCtrlAvoidObstacleFeedback const> StepCtrlAvoidObstacleFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator1> & lhs, const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_distance == rhs.obstacle_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator1> & lhs, const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c3bae86c954dc37799d101597cf8706";
  }

  static const char* value(const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c3bae86c954dc37ULL;
  static const uint64_t static_value2 = 0x799d101597cf8706ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/StepCtrlAvoidObstacleFeedback";
  }

  static const char* value(const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"float32 obstacle_distance #最近障碍物距离\n"
"\n"
;
  }

  static const char* value(const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepCtrlAvoidObstacleFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::StepCtrlAvoidObstacleFeedback_<ContainerAllocator>& v)
  {
    s << indent << "obstacle_distance: ";
    Printer<float>::stream(s, indent + "  ", v.obstacle_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_STEPCTRLAVOIDOBSTACLEFEEDBACK_H
