// Generated by gencpp from file woosh_msgs/TractorControlGoal.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_TRACTORCONTROLGOAL_H
#define WOOSH_MSGS_MESSAGE_TRACTORCONTROLGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace woosh_msgs
{
template <class ContainerAllocator>
struct TractorControlGoal_
{
  typedef TractorControlGoal_<ContainerAllocator> Type;

  TractorControlGoal_()
    : mode(0)
    , executeMode(0)  {
    }
  TractorControlGoal_(const ContainerAllocator& _alloc)
    : mode(0)
    , executeMode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _executeMode_type;
  _executeMode_type executeMode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CANCEL)
  #undef CANCEL
#endif
#if defined(_WIN32) && defined(EXCUTE)
  #undef EXCUTE
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(RESUM)
  #undef RESUM
#endif
#if defined(_WIN32) && defined(LOCK)
  #undef LOCK
#endif
#if defined(_WIN32) && defined(UNLOCK)
  #undef UNLOCK
#endif

  enum {
    CANCEL = 0u,
    EXCUTE = 1u,
    PAUSE = 2u,
    RESUM = 3u,
    LOCK = 1u,
    UNLOCK = 2u,
  };


  typedef boost::shared_ptr< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TractorControlGoal_

typedef ::woosh_msgs::TractorControlGoal_<std::allocator<void> > TractorControlGoal;

typedef boost::shared_ptr< ::woosh_msgs::TractorControlGoal > TractorControlGoalPtr;
typedef boost::shared_ptr< ::woosh_msgs::TractorControlGoal const> TractorControlGoalConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::woosh_msgs::TractorControlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::woosh_msgs::TractorControlGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::TractorControlGoal_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.executeMode == rhs.executeMode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::woosh_msgs::TractorControlGoal_<ContainerAllocator1> & lhs, const ::woosh_msgs::TractorControlGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace woosh_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2deb17c3e793646612225c03c12e682";
  }

  static const char* value(const ::woosh_msgs::TractorControlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2deb17c3e793646ULL;
  static const uint64_t static_value2 = 0x612225c03c12e682ULL;
};

template<class ContainerAllocator>
struct DataType< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "woosh_msgs/TractorControlGoal";
  }

  static const char* value(const ::woosh_msgs::TractorControlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 mode\n"
"uint8 executeMode\n"
"\n"
"#mode\n"
"uint8 CANCEL = 0\n"
"uint8 EXCUTE = 1\n"
"uint8 PAUSE = 2\n"
"uint8 RESUM = 3\n"
"\n"
"#executeMode\n"
"uint8 LOCK = 1\n"
"uint8 UNLOCK = 2\n"
;
  }

  static const char* value(const ::woosh_msgs::TractorControlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.executeMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TractorControlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::woosh_msgs::TractorControlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::woosh_msgs::TractorControlGoal_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "executeMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.executeMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_TRACTORCONTROLGOAL_H
