// Generated by gencpp from file woosh_msgs/TriggerWiFiReconnect.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_TRIGGERWIFIRECONNECT_H
#define WOOSH_MSGS_MESSAGE_TRIGGERWIFIRECONNECT_H

#include <ros/service_traits.h>


#include <woosh_msgs/TriggerWiFiReconnectRequest.h>
#include <woosh_msgs/TriggerWiFiReconnectResponse.h>


namespace woosh_msgs
{

struct TriggerWiFiReconnect
{

typedef TriggerWiFiReconnectRequest Request;
typedef TriggerWiFiReconnectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerWiFiReconnect
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::TriggerWiFiReconnect > {
  static const char* value()
  {
    return "adeb7eac4f60ecb52de64e214c385171";
  }

  static const char* value(const ::woosh_msgs::TriggerWiFiReconnect&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::TriggerWiFiReconnect > {
  static const char* value()
  {
    return "woosh_msgs/TriggerWiFiReconnect";
  }

  static const char* value(const ::woosh_msgs::TriggerWiFiReconnect&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::TriggerWiFiReconnectRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::TriggerWiFiReconnect >
template<>
struct MD5Sum< ::woosh_msgs::TriggerWiFiReconnectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::TriggerWiFiReconnect >::value();
  }
  static const char* value(const ::woosh_msgs::TriggerWiFiReconnectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::TriggerWiFiReconnectRequest> should match
// service_traits::DataType< ::woosh_msgs::TriggerWiFiReconnect >
template<>
struct DataType< ::woosh_msgs::TriggerWiFiReconnectRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::TriggerWiFiReconnect >::value();
  }
  static const char* value(const ::woosh_msgs::TriggerWiFiReconnectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::TriggerWiFiReconnectResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::TriggerWiFiReconnect >
template<>
struct MD5Sum< ::woosh_msgs::TriggerWiFiReconnectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::TriggerWiFiReconnect >::value();
  }
  static const char* value(const ::woosh_msgs::TriggerWiFiReconnectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::TriggerWiFiReconnectResponse> should match
// service_traits::DataType< ::woosh_msgs::TriggerWiFiReconnect >
template<>
struct DataType< ::woosh_msgs::TriggerWiFiReconnectResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::TriggerWiFiReconnect >::value();
  }
  static const char* value(const ::woosh_msgs::TriggerWiFiReconnectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_TRIGGERWIFIRECONNECT_H
