// Generated by gencpp from file woosh_msgs/WooshInit.msg
// DO NOT EDIT!


#ifndef WOOSH_MSGS_MESSAGE_WOOSHINIT_H
#define WOOSH_MSGS_MESSAGE_WOOSHINIT_H

#include <ros/service_traits.h>


#include <woosh_msgs/WooshInitRequest.h>
#include <woosh_msgs/WooshInitResponse.h>


namespace woosh_msgs
{

struct WooshInit
{

typedef WooshInitRequest Request;
typedef WooshInitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WooshInit
} // namespace woosh_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::woosh_msgs::WooshInit > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::woosh_msgs::WooshInit&) { return value(); }
};

template<>
struct DataType< ::woosh_msgs::WooshInit > {
  static const char* value()
  {
    return "woosh_msgs/WooshInit";
  }

  static const char* value(const ::woosh_msgs::WooshInit&) { return value(); }
};


// service_traits::MD5Sum< ::woosh_msgs::WooshInitRequest> should match
// service_traits::MD5Sum< ::woosh_msgs::WooshInit >
template<>
struct MD5Sum< ::woosh_msgs::WooshInitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::WooshInit >::value();
  }
  static const char* value(const ::woosh_msgs::WooshInitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::WooshInitRequest> should match
// service_traits::DataType< ::woosh_msgs::WooshInit >
template<>
struct DataType< ::woosh_msgs::WooshInitRequest>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::WooshInit >::value();
  }
  static const char* value(const ::woosh_msgs::WooshInitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::woosh_msgs::WooshInitResponse> should match
// service_traits::MD5Sum< ::woosh_msgs::WooshInit >
template<>
struct MD5Sum< ::woosh_msgs::WooshInitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::woosh_msgs::WooshInit >::value();
  }
  static const char* value(const ::woosh_msgs::WooshInitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::woosh_msgs::WooshInitResponse> should match
// service_traits::DataType< ::woosh_msgs::WooshInit >
template<>
struct DataType< ::woosh_msgs::WooshInitResponse>
{
  static const char* value()
  {
    return DataType< ::woosh_msgs::WooshInit >::value();
  }
  static const char* value(const ::woosh_msgs::WooshInitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOOSH_MSGS_MESSAGE_WOOSHINIT_H
